# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FARMtools
                                 A QGIS plugin
 This plugins is about geotecnoly and remote sensing tools
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-06-11
        copyright            : (C) 2026 by FARM Anytica
        email                : contato@farmanalytica.com.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FARMtools class from file FARMtools.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .farm_tools import FARMtools
    return FARMtools(iface)
