// Artigos da wiki — Português (Brasil). Tipos de seção: h2, p, list, steps, table, note.
export default [
  {
    slug: 'getting-started',
    icon: '🚀',
    title: 'Primeiros Passos',
    summary: 'Instale o plugin, configure o Google Earth Engine e autentique-se.',
    sections: [
      { p: 'O FARM tools é um plugin QGIS integrado ao Google Earth Engine (GEE). Antes de usar qualquer módulo você precisa do QGIS 3.28 ou mais recente, uma conta GEE gratuita e um projeto Google Cloud com a Earth Engine API habilitada.' },
      { h2: 'Instalação' },
      { steps: [
        'Abra o QGIS e vá em Complementos → Gerenciar e Instalar Complementos.',
        'Procure por "FARM tools" e clique em Instalar.',
        'Na primeira ativação o plugin baixa automaticamente seu pacote de dependências (earthengine-api, agrigee-lite e pacotes relacionados). Se o download falhar, ele usa o pip como alternativa; aguarde a tela de carregamento concluir.',
      ] },
      { note: 'As dependências são instaladas na pasta extlibs do próprio plugin e nunca substituem os pacotes que acompanham o QGIS (numpy, pandas etc.). Uma atualização do QGIS/Python reprovisiona tudo automaticamente.' },
      { h2: 'Configuração do Google Earth Engine' },
      { steps: [
        'Crie uma conta GEE gratuita em earthengine.google.com/signup.',
        'Crie um projeto Google Cloud em console.cloud.google.com e vincule-o à sua conta GEE.',
        'No Console Cloud, procure por "Earth Engine API" e habilite-a.',
        'Abra o Editor de Código do Earth Engine (code.earthengine.google.com) para encontrar seu ID de projeto.',
        'No QGIS, abra o FARM tools, clique em Configurar Autenticação, insira o ID do projeto e autorize o acesso na janela do navegador que abrir.',
      ] },
      { h2: 'Modos de autenticação' },
      { p: 'O FARM tools oferece duas formas de login no Earth Engine:' },
      { list: [
        'OAuth pessoal — entre com sua conta Google pelo navegador. Recomendado para usuários individuais.',
        'Conta de serviço — aponte o plugin para um arquivo de chave JSON de conta de serviço. Recomendado para máquinas compartilhadas, automação ou contas institucionais.',
      ] },
      { h2: 'Definindo uma área de interesse (AOI)' },
      { p: 'Todo módulo parte de uma AOI. Você pode desenhar um polígono diretamente no mapa do QGIS com a ferramenta de AOI ou selecionar uma camada vetorial existente. A AOI é convertida internamente para uma geometria WGS84 do Earth Engine, então qualquer CRS de projeto funciona.' },
      { note: 'Se você já usava o plugin RAVI, seu ID de projeto GEE, modo de autenticação e preferências de download são aproveitados automaticamente — o FARM tools compartilha essas chaves de configuração.' },
    ],
  },
  {
    slug: 'optical',
    icon: '🌿',
    title: 'Óptico (Sentinel-2)',
    summary: 'Séries temporais de índices de vegetação, filtragem de nuvens, composições e download multiespectral.',
    sections: [
      { p: 'O módulo Óptico trabalha com o acervo harmonizado de refletância de superfície Sentinel-2 (COPERNICUS/S2_SR_HARMONIZED): resolução de 10 m, revisita de ~5 dias, 12 bandas espectrais úteis mais a banda de qualidade SCL. É o carro-chefe para monitoramento de culturas e vegetação. Todo o processamento roda no Google Earth Engine, sem necessidade de baixar o acervo.' },
      { h2: 'Séries temporais de índices de vegetação' },
      { p: 'Monte uma série temporal de um índice espectral sobre sua AOI para qualquer intervalo de datas. Como uma AOI próxima à borda de um tile pode retornar mais de uma imagem por data, o módulo mantém exatamente uma cena por data (pontuada pela cobertura da AOI, com a nebulosidade do tile como desempate) e então faz a média do índice na AOI a 10 m para cada data.' },
      { p: 'São 19 índices embutidos, agrupados pelo que medem:' },
      { list: [
        'Vigor / verdor — NDVI, GNDVI, EVI, EVI2, SAVI, MSAVI, ARVI, VARI, TVI, SFDVI.',
        'Clorofila / red-edge — CIgreen, NDRE, ReCI, MTCI, MCARI, SIPI.',
        'Água, umidade & queimada — NDMI, NDWI, NBR.',
        'Personalizado — defina sua própria expressão de bandas (ex.: (B8 - B4) / (B8 + B4 + 0.5)); é validada por segurança e salva para reuso.',
      ] },
      { note: 'Nenhum índice é o melhor para tudo: o NDVI satura em dossel denso (prefira EVI/EVI2 ou índices de red-edge), os ajustados ao solo (SAVI/MSAVI) servem para cobertura esparsa, e os de red-edge/clorofila acompanham nitrogênio e clorofila.' },
      { h2: 'Máscara de nuvens (SCL)' },
      { p: 'Observações nubladas distorcem as séries. O FARM tools usa a Scene Classification Layer (SCL) do Sentinel-2 para mascarar nuvens, sombras, defeitos e cirros antes de calcular o índice. A máscara é fixada no início de uma análise e replicada de forma idêntica no gráfico, na amostragem por ponto/feição e nas composições — então todos os produtos descrevem os mesmos pixels de céu claro.' },
      { h2: 'Triagem de qualidade & suavização' },
      { p: 'Cada data carrega metadados de qualidade: nebulosidade do tile, percentual de pixels válidos dentro da AOI (o indicador mais confiável, medido a 10 m) e cobertura da cena. Depois de calculada, a série pode ser re-triada por esses limiares ou ter datas ligadas/desligadas individualmente, com o gráfico atualizando na hora — sem recalcular. Um filtro Savitzky-Golay opcional remove ruído da curva, preservando o tempo e a amplitude dos picos sazonais.' },
      { h2: 'Amostragem por ponto & por feição' },
      { p: 'Além da média da AOI, clique em um local para extrair o único pixel de 10 m sob ele (mais fiel a uma amostra de campo que uma média com buffer), ou calcule uma série média por feição de polígono rotulada por um campo de atributo — para comparar talhões ou zonas de manejo. Cada curva por geometria é plotada contra a linha de referência média da AOI, reusando o mesmo intervalo, índice e máscara.' },
      { h2: 'Imagem por data' },
      { p: 'Renderize qualquer data no QGIS, recortada na AOI (com buffer opcional de ±300 m) e exportada como GeoTIFF de 10 m em EPSG:4326: uma composição RGB / falsa-cor (cor verdadeira, presets NIR ou SWIR, realce 2–98%), ou o índice escolhido como raster pseudocolor contínuo.' },
      { h2: 'Composições & Área-Sob-a-Curva' },
      { p: 'Reduza as datas exibidas a um único mapa por uma estatística — média, mediana, mín, máx, amplitude (máx − mín), desvio-padrão, soma ou Área Sob a Curva (AUC). A AUC integra o índice no tempo pela regra do trapézio e é um proxy robusto de produtividade ou biomassa acumulada na safra.' },
      { h2: 'Download multiespectral' },
      { p: 'Baixe em lote a pilha multiespectral completa (ou bandas selecionadas) da sua AOI como GeoTIFF, para uma ou várias datas. Os downloads rodam em segundo plano, então o QGIS continua responsivo.' },
      { h2: 'Sobreposição climática' },
      { p: 'Opcionalmente, sobreponha a precipitação mensal NASA POWER como barras sob a curva de vegetação para interpretar a dinâmica dos índices frente a eventos meteorológicos — veja o artigo ClimaPlots.' },
    ],
  },
  {
    slug: 'landsat',
    icon: '🛰️',
    title: 'Landsat',
    summary: 'Séries temporais de décadas e imagens para monitoramento histórico.',
    sections: [
      { p: 'O módulo Landsat alcança 1999 — Landsat 7, 8 e 9 (USGS Coleção 2, Tier 1) — sendo a escolha certa para análise histórica de uso da terra, desempenho de culturas no longo prazo e detecção de mudanças anteriores à era Sentinel (2015+). O Landsat 5 é deliberadamente excluído: seu sensor TM não tem banda pancromática, então o produto pan-sharpened de 15 m não pode ser construído a partir dele.' },
      { h2: 'Olhe no TOA, meça no SR' },
      { p: 'Dois produtos fisicamente distintos são usados, cada um para a tarefa que melhor lhe cabe. A imagem nítida de 15 m em cor verdadeira vem da refletância no Topo da Atmosfera (TOA), onde o detalhe espacial importa mais que a calibração absoluta; todos os índices e composições quantitativos são calculados sobre a Refletância de Superfície (SR) corrigida, a 30 m.' },
      { h2: 'Cor verdadeira pan-sharpened de 15 m' },
      { p: 'O pan-sharpening HSV dobra o detalhe aparente da imagem em cor verdadeira: o RGB de 30 m é convertido para Matiz–Saturação–Valor, a banda pancromática de 15 m substitui o canal de brilho (valor) e o resultado volta para RGB — tomando a cor das bandas de 30 m e o detalhe da banda pan de 15 m. Ideal para delinear limites de talhões, estradas e pequenas feições.' },
      { h2: 'Índices espectrais & composições' },
      { p: 'São oferecidos 14 índices em Refletância de Superfície (nenhum exige red-edge, que o Landsat não tem): vigor — NDVI, GNDVI, EVI, EVI2; ajustados ao solo — SAVI, OSAVI, MSAVI; atmosfera/clorofila — ARVI, CIgreen, CIred, MCARI; água e solo exposto — NDWI (NIR–SWIR1), MNDWI, BSI. Para interpretação qualitativa há quatro combinações de bandas: cor real, falsa-cor (NIR·Vermelho·Verde), SWIR1·NIR·Vermelho e SWIR2·NIR·Verde.' },
      { h2: 'Séries temporais longas (SITS)' },
      { p: 'Uma Série Temporal de Imagens de Satélite do índice escolhido é construída em todo o acervo, reduzida sobre a AOI pela mediana espacial (padrão; média disponível). Cada missão é consultada dentro de sua própria vida útil e as séries Landsat 7/8/9 são mescladas em um registro cronológico, colorido por missão, dando um histórico contínuo de índice de 1999 até hoje.' },
      { h2: 'Descoberta & download de cenas' },
      { p: 'As cenas são mascaradas para nuvens (bitmask QA_PIXEL em tudo, mais uma passagem de Simple Cloud Score no TOA) e mantidas apenas se passarem no filtro de cobertura mínima válida (padrão 80% de pixels claros dentro da AOI) — então você nunca vê uma data majoritariamente nublada ou fora do quadro. Pré-visualize as datas no mapa e baixe como GeoTIFF; com a biblioteca agrigee-lite, o módulo também suporta download em lote e em super-resolução.' },
      { note: 'A revisita do Landsat (16 dias por satélite, ~8 dias para L8+L9 combinados) e a resolução de 30 m são mais grosseiras que o Sentinel-2 — prefira o módulo Óptico para a safra atual e o Landsat para o histórico. O corretor de linha de varredura do Landsat 7 falhou em 2003, deixando lacunas listradas; prefira Landsat 8/9 para trabalho sem falhas pós-2013.' },
    ],
  },
  {
    slug: 'sar',
    icon: '📡',
    title: 'SAR (Sentinel-1)',
    summary: 'Análise de retroespalhamento de radar independente de nuvens.',
    sections: [
      { p: 'O Radar de Abertura Sintética (SAR) ilumina ativamente o solo com micro-ondas e mede o sinal retornado (retroespalhamento). Diferente dos sensores ópticos, funciona através de nuvens, fumaça e à noite — essencial em estações chuvosas, quando as séries ópticas têm lacunas.' },
      { h2: 'O que o retroespalhamento revela' },
      { list: [
        'Rugosidade da superfície — solo preparado, dossel em crescimento e áreas colhidas retornam assinaturas distintas.',
        'Umidade — solo e vegetação úmidos refletem mais, útil para monitorar irrigação e inundações.',
        'Estrutura — as polarizações VV e VH respondem de forma diferente a hastes verticais e a volume foliar.',
      ] },
      { h2: 'Pipeline de Dados Prontos para Análise (ARD)' },
      { p: 'Cenas brutas Ground Range Detected (GRD) em modo Interferometric Wide são padronizadas seguindo o framework ARD Sentinel-1 de Mullissa et al. (2021), com três correções independentemente ativáveis (todas ligadas por padrão):' },
      { list: [
        'Remoção de ruído de borda — descarta as margens ruidosas da cena (ângulos de incidência fora de ~30,6°–45,2°).',
        'Filtragem de speckle — um filtro Gamma-MAP multitemporal suprime o speckle granuloso preservando bordas (Lee, Refined Lee, Lee-Sigma, Boxcar também disponíveis).',
        'Nivelamento radiométrico de terreno — normaliza o retroespalhamento para gamma-naught (γ⁰) nivelado usando um DEM, para que a mesma cobertura pareça igual em terreno plano e inclinado.',
      ] },
      { p: 'A órbita é fixada na passagem descendente para que toda observação de uma série compartilhe uma geometria de visada. A saída é entregue em decibéis (dB) por padrão, ou em potência linear.' },
      { h2: 'Índices de dupla polarização' },
      { p: 'A partir de VV e VH, nove índices de radar são derivados — VV/VH Ratio, RVI, DpRVI, CR, NDPI, PD, DPSVIm, PRVI e mRVI. Os orientados à vegetação (RVI, DpRVI, mRVI, PRVI) sobem ao longo da safra à medida que o dossel despolariza o sinal — um análogo de radar à curva de crescimento do NDVI, sem interrupção por nuvens — enquanto os índices de diferença/razão acompanham a transição entre os regimes de solo exposto, vegetado e colhido.' },
      { h2: 'Série temporal, composições & renderização' },
      { p: 'A média na AOI de qualquer índice (ou VV/VH bruto) é plotada como uma série temporal densa e independente do clima. Além disso, exporte uma data única (VV, VH e os nove índices) ou uma composição reduzida por média, mediana, mín, máx, amplitude, desvio-padrão, soma ou AUC. As imagens renderizam de dois modos: composição RGB (qualitativa — a cor revela contrastes de cobertura) ou pseudocolor de banda única (quantitativa — cada cor mapeia um valor numa legenda).' },
      { note: 'Valores SAR são em decibéis (dB) e tipicamente negativos — ex.: ≈ −20 dB ou menos para superfícies lisas/secas e água aberta, −15 a −8 dB para vegetação, mais altos para áreas urbanas ou alvos úmidos/inundados. O retroespalhamento sobe também com a umidade da superfície, então um clareamento súbito pode ser chuva ou irrigação, não crescimento. A variação relativa no tempo importa mais que os valores absolutos; prefira estatísticas de área a pixels isolados.' },
    ],
  },
  {
    slug: 'dem',
    icon: '⛰️',
    title: 'DEM & Terreno',
    summary: 'Navegação no catálogo de elevação, downloads cientes da AOI e renderização Magma.',
    sections: [
      { p: 'O módulo DEM entrega dados de elevação prontos para uso em qualquer AOI a partir de um catálogo curado de cerca de trinta Modelos Digitais de Elevação públicos — de produtos globais de radar/óptico a LiDAR nacional submétrico — como superfície base para planejamento de drenagem, terraceamento, orientação de máquinas e análise de erosão.' },
      { p: 'Uma distinção-chave atravessa o catálogo: um Modelo Digital de Terreno (DTM) é o solo nu (vegetação e construções removidas — melhor para hidrologia e análise de superfície), enquanto um Modelo Digital de Superfície (DSM) é o topo da superfície, incluindo dossel e telhados.' },
      { h2: 'Catálogo de elevação' },
      { p: 'Navegue por produtos globais (Copernicus GLO-30, NASADEM, SRTM, ALOS AW3D30, ASTER, MERIT…) e LiDAR regional/nacional (USGS 3DEP, AHN da Holanda, Inglaterra, RGE ALTI da França, Austrália, ArcticDEM/REMA…). Para a maioria dos trabalhos os produtos globais de 30 m são o padrão prático; escolha LiDAR nacional pela precisão onde cobre a AOI, MERIT/DEM-H para consistência hidrológica e os modelos polares para gelo e altas latitudes.' },
      { h2: 'Disponibilidade ciente da AOI' },
      { p: 'Definida a AOI, o catálogo é filtrado para oferecer só os conjuntos que de fato a cobrem: uma triagem rápida por caixa delimitadora descarta produtos regionais que não se sobrepõem, e então uma checagem ao vivo no Earth Engine confirma que há pixels reais dentro da AOI. O resultado é uma lista curta e confiável. (Sem login no GEE, a checagem ao vivo é pulada e o catálogo completo é mostrado para navegação.)' },
      { h2: 'Recorte, buffer & exportação' },
      { p: 'Opcionalmente aplique buffer à AOI de −300 m a +300 m; então o modelo é mascarado pela AOI (pixels fora viram no-data transparente) e exportado como GeoTIFF de ponto flutuante em EPSG:4326. A exportação é numa grade fixa de 30 m independentemente da resolução nativa — então uma fonte LiDAR de 0,5 m ou 1 m é reamostrada para 30 m na exportação; os modelos nacionais finos valem aqui pela precisão e qualidade de solo nu, não pelo detalhe entregue.' },
      { h2: 'Renderização' },
      { p: 'O raster baixado é estilizado como camada pseudocolor de banda única usando a rampa Magma perceptualmente uniforme, esticada entre os valores mín e máx locais da AOI — então as cores são relativas à área mostrada. Leia a faixa de valores para ancorar as cores a alturas reais.' },
      { note: 'O módulo entrega apenas a superfície de elevação bruta — não calcula declividade, orientação, sombreamento (hillshade), curvas de nível ou direção de fluxo. Gere isso no QGIS a partir do raster baixado, para que método e parâmetros fiquem explícitos. Os datums verticais diferem entre produtos, então as alturas não são diretamente comparáveis sem redução a uma referência comum.' },
    ],
  },
  {
    slug: 'sysi',
    icon: '🟤',
    title: 'SYSI Solo Exposto',
    summary: 'Composições sintéticas de solo exposto para mapeamento de solos.',
    sections: [
      { p: 'O SYSI (Synthetic Soil Image) constrói uma composição em que cada pixel mostra a superfície do solo livre de vegetação — mesmo que nenhuma data isolada mostre toda a área exposta. Construído a partir do acervo harmonizado de refletância de superfície Sentinel-2 (de 2017 em diante) a 10 m, é um insumo-chave para mapeamento digital de solos, delineamento de classes de solo e zonas de manejo. A regra de solo exposto segue o método GEOS3 de Demattê et al. (2018).' },
      { h2: 'Como funciona' },
      { steps: [
        'Você define a AOI, um intervalo de datas, os meses do calendário a incluir, uma cobertura máxima de nuvens e as faixas de limiar de NDVI/NBR2.',
        'Cada cena é triada para nuvens (QA60); então quatro grandezas diagnósticas são calculadas por pixel: NDVI, NBR2 e os termos de inclinação no visível.',
        'Um pixel é mantido como solo exposto só quando as cinco condições do GEOS3 valem — NDVI baixo (remove vegetação verde), NBR2 na faixa (remove palhada/resíduo seco), forma espectral de solo e uma inclinação crescente azul→verde→vermelho no visível.',
        'As observações de solo exposto sobreviventes são reduzidas por pixel pela mediana temporal, robusta a outliers e que preenche naturalmente as lacunas das datas em que cada pixel estava exposto.',
        'O resultado é uma imagem de 9 bandas a 10 m (Azul, Verde, Vermelho, Red-edge 2, NIR, SWIR1, SWIR2, NDVI, NBR2), renderizada no QGIS e exportável como GeoTIFF.',
      ] },
      { note: 'Restrinja os meses à estação local de pousio/preparo, quando o solo tende a estar mais exposto. Faixas de NDVI/NBR2 permissivas admitem vegetação esparsa ou resíduo; faixas estritas descartam solo válido e reduzem a cobertura.' },
      { h2: 'O que fazer com um SYSI' },
      { list: [
        'Delinear classes de solo e transições visualmente — diferenças de cor acompanham textura e matéria orgânica.',
        'Apoiar o plano de amostragem: posicione amostras de solo onde a composição mostra zonas distintas.',
        'Alimentar modelos de mapeamento digital de solos com um preditor espectral estável.',
      ] },
      { note: 'Áreas que nunca ficaram expostas no período analisado (pastagem permanente, floresta) ficam vazias na composição — amplie o intervalo de datas para melhorar a cobertura.' },
    ],
  },
  {
    slug: 'climaplots',
    icon: '🌦️',
    title: 'ClimaPlots',
    summary: 'Diagnóstico climático de qualquer ponto: tendências, diagrama climático, índices de extremos e seca (SPI).',
    sections: [
      { p: 'O ClimaPlots transforma décadas de dados climáticos diários em grade, para um ponto que você clica (ou digita), em um diagnóstico climático compacto — tendências de longo prazo, o regime sazonal médio, índices padronizados de extremos climáticos e um índice de seca. Não exige conta GEE nem estação meteorológica; os dados são gratuitos e globalmente consistentes.' },
      { h2: 'Dois conjuntos de dados intercambiáveis' },
      { list: [
        'NASA POWER — meteorologia diária satélite/modelo com correção de viés, global, 1981 → presente (~0,5°).',
        'Reanálise ERA5 / ERA5-Land (via Open-Meteo) — registro sem lacunas e fisicamente consistente, global, 1940 → presente (~0,25°/0,1°).',
      ] },
      { p: 'Você pode sobrepor um segundo ponto B que pode até usar a outra fonte, então o mesmo local pode ser comparado entre os dois conjuntos. Ambos são harmonizados a um conjunto comum de variáveis e unidades: temperatura máx/mín (°C), precipitação (mm/dia), umidade relativa (%), irradiação (kWh/m²/dia) e velocidade do vento (m/s).' },
      { h2: 'Variáveis agronômicas derivadas' },
      { p: 'Duas variáveis são calculadas a partir da temperatura: Graus-Dia (calor acumulado acima de uma base de 10 °C) e evapotranspiração de referência ET0 (demanda hídrica atmosférica). A ET0 usa a equação de Hargreaves (baseada em temperatura) para o POWER, enquanto o Open-Meteo fornece sua própria ET0 FAO-56 Penman–Monteith diretamente.' },
      { h2: 'Tendências anuais & estatística' },
      { p: 'Cada série anual (somas para precipitação, ET0, GDD; médias para o resto) é testada com dois testes não-paramétricos a α = 0,05: o teste de tendência de Mann–Kendall (crescente / decrescente / sem tendência, com p-valor) e o teste de ponto de mudança de Pettitt (homogêneo, ou um ano provável de quebra). Ambos os veredictos aparecem no título do gráfico.' },
      { h2: 'Diagrama termopluviométrico' },
      { p: 'Um diagrama estilo Walter–Lieth do ciclo médio anual — doze barras de chuva mensal média com linhas de temperatura média máx/mín em eixo secundário — para identificar estações seca e úmida e períodos de provável déficit hídrico.' },
      { h2: 'Índices de extremos ETCCDI' },
      { p: 'Um painel padronizado de índices de mudança climática da OMM calculados a partir de dados diários: dias de geada, noites tropicais, dias de gelo, dias de verão; TXx/TXn e TNx/TNn mensais e amplitude térmica diária; e para precipitação Rx1day/Rx5day, R10mm/R20mm, SDII e dias secos/úmidos consecutivos (CDD/CWD).' },
      { h2: 'Índice de Precipitação Padronizada (SPI)' },
      { p: 'Um SPI de 90 dias expressa a chuva como uma anomalia estatística ajustada por gama, em unidades de desvio-padrão, comparável entre climas: excursões negativas sustentadas marcam secas, positivas marcam períodos úmidos (|SPI| ≥ 2 é extremo).' },
      { h2: 'Usos típicos' },
      { list: [
        'Explicar anomalias em séries de NDVI — quedas após geada, platôs durante seca.',
        'Avaliar a mudança climática recente em uma fazenda, área experimental ou bacia.',
        'Documentar o contexto meteorológico em relatórios de campo; no módulo Óptico a série de chuva pode ser sobreposta ao gráfico de vegetação.',
      ] },
      { note: 'Os valores são em grade, não de estação — microclimas topográficos/costeiros abruptos são suavizados. POWER e ERA5 diferem em método, resolução e ano inicial, então o mesmo ponto pode dar valores ou tendências um pouco diferentes; compará-los via ponto B é informativo. Os resultados de tendência dependem da janela escolhida — prefira o período defensável mais longo.' },
    ],
  },
  {
    slug: 'fieldguide',
    icon: '📍',
    title: 'Guia de Campo',
    summary: 'Captura de pontos, amostragem de polígonos, pontos ótimos por raster, rotas e exportações.',
    sections: [
      { p: 'O Guia de Campo transforma o mapa do QGIS em um planejador de campanhas de campo: capture pontos de amostragem, gere-os automaticamente a partir de talhões (geométrico ou otimizado por raster), abra rotas de carro e exporte a sessão como CSV, GPX, camada QGIS ou relatório PDF para celular.' },
      { p: 'Todos os pontos são armazenados internamente em WGS84 (EPSG:4326), independentemente do CRS do projeto, com precisão de 8 decimais (~1 mm) — as coordenadas atravessam todas as exportações sem perda.' },
      { h2: 'Captura manual & entrada de coordenadas' },
      { list: [
        'Capturar pontos no mapa: cada clique adiciona um marcador numerado. A ferramenta restaura a ferramenta de mapa anterior ao ser desligada e nunca sequestra o canvas permanentemente.',
        'Entrada manual: digite latitude/longitude diretamente. Vírgula e ponto decimais são aceitos (-23,5505 ≡ -23.5505), com validação de intervalo.',
      ] },
      { h2: 'Amostragem de polígonos (geométrica)' },
      { p: 'Gere pontos de amostra para cada feição de uma camada de polígonos. A quantidade é fixa por feição (1–50) ou por densidade (uma marca a cada N hectares, medidos elipsoidalmente). Métodos de distribuição:' },
      { list: [
        'Centroide — um ponto no centroide do polígono; rápido para talhões compactos.',
        'Distribuição otimizada (padrão) — seleção maximin gulosa que aproxima um desenho de preenchimento de espaço, robusta em formas irregulares; saída ordenada para um caminhamento estável.',
        'Grade sistemática — grade alinhada ao eixo longo do talhão (via PCA da nuvem de candidatos), não ao norte do mapa.',
        'Transecto em zigue-zague — o clássico caminhamento serpentina de amostragem de solo ao longo do eixo maior do talhão.',
      ] },
      { p: 'Os pontos são mantidos longe das bordas por um buffer interno automático (3–12% do tamanho do talhão), evitando efeitos de borda como pixels misturados e cabeceiras de máquina. A amostragem é determinística: mesma camada, método e quantidade sempre produzem os mesmos pontos — planos reproduzíveis e auditáveis.' },
      { h2: 'Pontos ótimos baseados em raster' },
      { p: 'Em vez de posicionamento geométrico, deixe os dados decidirem: um ponto por polígono no local de valor máximo do raster (ex.: pico de uma composição NDVI), para que a equipe de campo visite o ponto mais representativo fisiologicamente de cada talhão.' },
      { steps: [
        'Habilite "Usar seleção de ponto ótimo baseada em raster".',
        'Escolha a camada raster e a banda.',
        'Os pontos são calculados imediatamente — o polígono é reprojetado para o CRS do raster (o raster nunca é reamostrado), mascarado pela geometria exata, limpo de no-data e ruído de borda, e o máximo suavizado é selecionado.',
      ] },
      { p: 'Casos extremos são tratados explicitamente: polígonos totalmente nublados são pulados e contabilizados, polígonos sub-pixel são sinalizados, e basemaps web (XYZ, WMS) são rejeitados de antemão por não terem grade de pixels legível. Nome do raster, banda, CRS e o valor em cada ponto acompanham todas as exportações, garantindo rastreabilidade total.' },
      { h2: 'Rotas (Google Maps)' },
      { p: 'Abra os pontos da sessão como rota de carro ordenada no Google Maps. Sessões longas são divididas em segmentos de 10 pontos com sobreposição de 1 ponto, mantendo a continuidade em rotas multissegmento.' },
      { h2: 'Exportações' },
      { table: {
        headers: ['Formato', 'Conteúdo'],
        rows: [
          ['CSV', 'ordem, longitude, latitude (8 decimais); colunas de fonte do raster, método e valor quando a seleção por raster foi usada'],
          ['GPX', 'Waypoints FG001…FGnnn (compatíveis com GPS de mão) mais uma rota ordenada; metadados do raster nas descrições'],
          ['Camada temporária', 'Camada de pontos em memória no CRS do projeto com atributos ordem/nome/lon/lat'],
          ['Relatório PDF', 'Captura do mapa mais um cartão por ponto com link para o Google Maps; rodapé com a metodologia do raster quando aplicável'],
        ],
      } },
      { h2: 'Gerenciamento da sessão' },
      { list: [
        'Lista de pontos ao vivo com contagem e prontidão de rota.',
        'Remover último, excluir selecionado (numeração permanece contígua) e limpar com confirmação.',
        'Aviso Anexar / Substituir protege o trabalho existente ao gerar ou importar em uma sessão não vazia.',
        'Importação CSV: exige cabeçalhos longitude/latitude (qualquer ordem, sem distinção de maiúsculas), aceita vírgula decimal e informa as linhas puladas.',
      ] },
    ],
  },
  {
    slug: 'mapbiomas',
    icon: '🗺️',
    title: 'MapBiomas',
    summary: 'Uso e cobertura da terra do Brasil por ano e análise configurável de transições.',
    sections: [
      { p: 'O MapBiomas traz o acervo anual de uso e cobertura da terra da Coleção 9 do MapBiomas Brasil para o QGIS. Explore qualquer ano dentro do módulo, baixe um ano para o QGIS como raster de classificação estilizado, ou analise como a terra mudou ao longo do tempo. A cobertura é apenas do Brasil e usa o Google Earth Engine.' },
      { h2: 'Cobertura' },
      { list: [
        'Explore todos os anos (1985–2023) no módulo com um controle deslizante de ano, ao lado da legenda oficial de 63 classes.',
        'Baixe qualquer ano para o QGIS como um raster de classificação de banda única estilizado com a paleta oficial do MapBiomas — IDs de classe reais, mantendo os pixels consultáveis e analisáveis.',
      ] },
      { h2: 'Análise de transição' },
      { p: 'Mapeie o primeiro ano em que cada pixel mudou de um uso de origem para um uso de destino, e visualize a área convertida por ano.' },
      { list: [
        'Predefinições: Pastagem → Lavoura, Desmatamento (floresta → antrópico), Regeneração florestal, Expansão agrícola e Expansão urbana.',
        'Personalizado: escolha qualquer combinação de classes de origem e destino.',
        'Um controle de intervalo de anos filtra o gráfico em tempo real e limita a camada de transição exportada, que carrega no QGIS classificada por ano de transição.',
      ] },
      { note: 'A Coleção 9 do MapBiomas cobre apenas o Brasil — áreas fora do Brasil retornam resultados vazios. Requer autenticação no Google Earth Engine, como os demais módulos GEE.' },
    ],
  },
  {
    slug: 'exports-downloads',
    icon: '💾',
    title: 'Exportações & Downloads',
    summary: 'Formatos de saída de todos os módulos e onde os arquivos são salvos.',
    sections: [
      { p: 'Todos os módulos do FARM tools produzem formatos padrão e portáveis, que abrem no QGIS e além.' },
      { table: {
        headers: ['Módulo', 'Saídas'],
        rows: [
          ['Óptico', 'Séries de índices (gráfico + CSV), imagens e composições GeoTIFF, download multiespectral em lote'],
          ['Landsat', 'Séries temporais, cenas GeoTIFF, downloads em lote e super-resolução'],
          ['SAR', 'Séries e gráficos de retroespalhamento, camadas raster estilizadas, download GeoTIFF'],
          ['DEM', 'Elevação GeoTIFF recortada, renderização hillshade/terreno'],
          ['SYSI', 'Composição sintética de solo exposto como camada renderizada / GeoTIFF'],
          ['ClimaPlots', 'Gráficos e dados de séries climáticas'],
          ['Guia de Campo', 'CSV, GPX, camada temporária QGIS, relatório PDF, rotas Google Maps'],
          ['MapBiomas', 'GeoTIFF de classificação por ano e GeoTIFF de transição (classificado por ano de transição), camadas estilizadas por paleta'],
        ],
      } },
      { h2: 'Pasta de download & proxy' },
      { p: 'A pasta padrão de download e um proxy HTTP(S) opcional são configurados nas preferências do plugin e persistem entre sessões. Todos os downloads pesados rodam em segundo plano — você pode continuar trabalhando no QGIS enquanto concluem.' },
    ],
  },
  {
    slug: 'faq',
    icon: '❓',
    title: 'FAQ & Solução de Problemas',
    summary: 'Problemas comuns: autenticação, dependências, proxies e convivência com o RAVI.',
    sections: [
      { h2: 'A autenticação falha ou pede login toda sessão' },
      { list: [
        'Confirme que a Earth Engine API está habilitada no seu projeto Cloud (Console Cloud → APIs).',
        'Confirme que o ID informado é o ID do projeto Cloud, não o nome do projeto.',
        'O OAuth pessoal abre uma janela do navegador — se ela nunca aparecer, verifique seu navegador padrão e bloqueadores de popup.',
        'Para contas de serviço: o caminho da chave JSON deve ser legível e a conta de serviço deve estar registrada para uso do Earth Engine.',
      ] },
      { h2: 'Problemas na instalação de dependências' },
      { list: [
        'O primeiro carregamento baixa um pacote de dependências pré-compilado para a sua versão de Python do QGIS; em caso de falha, usa o pip. Ambos precisam de internet.',
        'Atrás de firewall corporativo, configure a URL do proxy nas preferências do plugin e reinicie o QGIS.',
        'Após atualizar o QGIS (nova versão de Python), as dependências são reprovisionadas automaticamente no próximo carregamento.',
      ] },
      { h2: 'Gráficos ou downloads vêm vazios' },
      { list: [
        'Verifique se a AOI realmente intersecta imagens disponíveis no intervalo de datas selecionado.',
        'No Sentinel-2, um limite de nuvens muito rígido pode filtrar todas as cenas — relaxe o limite e tente de novo.',
        'O GEE tem cotas de uso; AOIs muito grandes ou períodos longos podem precisar ser divididos.',
      ] },
      { h2: 'Posso usar o FARM tools junto com o RAVI?' },
      { p: 'Sim. O FARM tools é um fork do plugin RAVI com identidade própria (pasta, menu, barra de ferramentas) e foi projetado para conviver com o RAVI no mesmo perfil do QGIS. O login no GEE e as preferências de download são compartilhados de propósito, então uma configuração existente do RAVI é aproveitada.' },
      { h2: 'Quais versões do QGIS são suportadas?' },
      { p: 'QGIS 3.28 ou mais recente (Python 3.11–3.13). O QGIS 3.44 LTR com Python 3.12 é a plataforma de referência.' },
      { h2: 'Onde reporto bugs ou peço funcionalidades?' },
      { p: 'Abra uma issue em github.com/farmanalytica/farm_tools/issues. Para suporte comercial e soluções personalizadas, fale com a FARM Analytica pelo WhatsApp ou adm@farmanalytica.com.br.' },
    ],
  },
]
