// Artigos da wiki — Português (Brasil). Tipos de seção: h2, p, list, steps, table, note.
export default [
  {
    slug: 'getting-started',
    icon: '🚀',
    title: 'Primeiros Passos',
    summary: 'Instale o plugin, configure o Google Earth Engine e autentique-se.',
    sections: [
      { p: 'O FARM tools é um plugin QGIS integrado ao Google Earth Engine (GEE). Antes de usar qualquer módulo você precisa do QGIS 3.28 ou mais recente, uma conta GEE gratuita e um projeto Google Cloud com a Earth Engine API habilitada.' },
      { h2: 'Instalação' },
      { steps: [
        'Abra o QGIS e vá em Complementos → Gerenciar e Instalar Complementos.',
        'Procure por "FARM tools" e clique em Instalar.',
        'Na primeira ativação o plugin baixa automaticamente seu pacote de dependências (earthengine-api, agrigee-lite e pacotes relacionados). Se o download falhar, ele usa o pip como alternativa; aguarde a tela de carregamento concluir.',
      ] },
      { note: 'As dependências são instaladas na pasta extlibs do próprio plugin e nunca substituem os pacotes que acompanham o QGIS (numpy, pandas etc.). Uma atualização do QGIS/Python reprovisiona tudo automaticamente.' },
      { h2: 'Configuração do Google Earth Engine' },
      { steps: [
        'Crie uma conta GEE gratuita em earthengine.google.com/signup.',
        'Crie um projeto Google Cloud em console.cloud.google.com e vincule-o à sua conta GEE.',
        'No Console Cloud, procure por "Earth Engine API" e habilite-a.',
        'Abra o Editor de Código do Earth Engine (code.earthengine.google.com) para encontrar seu ID de projeto.',
        'No QGIS, abra o FARM tools, clique em Configurar Autenticação, insira o ID do projeto e autorize o acesso na janela do navegador que abrir.',
      ] },
      { h2: 'Modos de autenticação' },
      { p: 'O FARM tools oferece duas formas de login no Earth Engine:' },
      { list: [
        'OAuth pessoal — entre com sua conta Google pelo navegador. Recomendado para usuários individuais.',
        'Conta de serviço — aponte o plugin para um arquivo de chave JSON de conta de serviço. Recomendado para máquinas compartilhadas, automação ou contas institucionais.',
      ] },
      { h2: 'Definindo uma área de interesse (AOI)' },
      { p: 'Todo módulo parte de uma AOI. Você pode desenhar um polígono diretamente no mapa do QGIS com a ferramenta de AOI ou selecionar uma camada vetorial existente. A AOI é convertida internamente para uma geometria WGS84 do Earth Engine, então qualquer CRS de projeto funciona.' },
      { note: 'Se você já usava o plugin RAVI, seu ID de projeto GEE, modo de autenticação e preferências de download são aproveitados automaticamente — o FARM tools compartilha essas chaves de configuração.' },
    ],
  },
  {
    slug: 'optical',
    icon: '🌿',
    title: 'Óptico (Sentinel-2)',
    summary: 'Séries temporais de índices de vegetação, filtragem de nuvens, composições e download multiespectral.',
    sections: [
      { p: 'O módulo Óptico trabalha com imagens Sentinel-2: resolução de 10 m, revisita de 5 dias e 13 bandas espectrais. É o carro-chefe para monitoramento de culturas e vegetação.' },
      { h2: 'Séries temporais de índices de vegetação' },
      { p: 'Monte uma série temporal de um índice de vegetação sobre sua AOI para qualquer intervalo de datas. Índices suportados incluem:' },
      { list: [
        'NDVI — Índice de Vegetação por Diferença Normalizada, a medida padrão de vigor.',
        'EVI — Índice de Vegetação Melhorado, menos sujeito à saturação em dosséis densos.',
        'SAVI — Índice de Vegetação Ajustado ao Solo, corrige o brilho do solo em vegetação esparsa.',
        'GNDVI — NDVI Verde, mais sensível à clorofila e ao status de nitrogênio.',
      ] },
      { p: 'A série pode ser calculada por ponto ou por feição (ex.: por talhão), e os resultados aparecem em um gráfico interativo que você pode inspecionar data a data.' },
      { h2: 'Filtragem de nuvens (SCL)' },
      { p: 'Observações nubladas distorcem as séries. O FARM tools usa a Scene Classification Layer (SCL) do Sentinel-2 para mascarar nuvens, sombras e cirros antes de calcular os índices, e permite definir um limite máximo de cobertura de nuvens para as cenas incluídas na série.' },
      { h2: 'Pré-visualização & composições' },
      { p: 'Visualize qualquer data como imagem RGB ou colorida por índice diretamente no mapa do QGIS antes de baixar. Você também pode criar composições (ex.: mediana de um período) para obter uma síntese livre de nuvens da sua AOI.' },
      { h2: 'Download multiespectral' },
      { p: 'Baixe a pilha multiespectral completa (ou bandas selecionadas) da sua AOI como GeoTIFF, em lote, para uma ou várias datas. Os downloads rodam em segundo plano, então o QGIS continua responsivo.' },
      { h2: 'Sobreposição climática' },
      { p: 'Opcionalmente, sobreponha séries climáticas NASA POWER (precipitação, temperatura) no gráfico de vegetação para interpretar a dinâmica dos índices frente a eventos meteorológicos — veja o artigo ClimaPlots.' },
    ],
  },
  {
    slug: 'landsat',
    icon: '🛰️',
    title: 'Landsat',
    summary: 'Séries temporais de décadas e imagens para monitoramento histórico.',
    sections: [
      { p: 'O módulo Landsat alcança décadas de histórico — Landsat 5, 7, 8 e 9 — sendo a escolha certa para análise histórica de uso da terra, desempenho de culturas no longo prazo e detecção de mudanças anteriores à era Sentinel (2015+).' },
      { h2: 'Séries temporais longas' },
      { p: 'Calcule séries de índices de vegetação em todo o acervo Landsat para sua AOI. Use para comparar safras entre décadas, detectar tendências de degradação ou recuperação e documentar o histórico de uso de um talhão.' },
      { h2: 'Pré-visualização & download de cenas' },
      { p: 'Navegue pelas cenas disponíveis para sua AOI e intervalo de datas, visualize no mapa e baixe como GeoTIFF.' },
      { h2: 'Download em lote & super-resolução' },
      { p: 'Com a biblioteca agrigee-lite, o módulo suporta download em lote de muitas cenas de uma vez e downloads em super-resolução, que refinam a resolução nativa de 30 m do Landsat para análise visual.' },
      { note: 'A revisita do Landsat (16 dias por satélite) e a resolução de 30 m são mais grosseiras que o Sentinel-2 — prefira o módulo Óptico para monitorar a safra atual e o Landsat para o histórico.' },
    ],
  },
  {
    slug: 'sar',
    icon: '📡',
    title: 'SAR (Sentinel-1)',
    summary: 'Análise de retroespalhamento de radar independente de nuvens.',
    sections: [
      { p: 'O Radar de Abertura Sintética (SAR) ilumina ativamente o solo com micro-ondas e mede o sinal retornado (retroespalhamento). Diferente dos sensores ópticos, funciona através de nuvens, fumaça e à noite — essencial em estações chuvosas, quando as séries ópticas têm lacunas.' },
      { h2: 'O que o retroespalhamento revela' },
      { list: [
        'Rugosidade da superfície — solo preparado, dossel em crescimento e áreas colhidas retornam assinaturas distintas.',
        'Umidade — solo e vegetação úmidos refletem mais, útil para monitorar irrigação e inundações.',
        'Estrutura — as polarizações VV e VH respondem de forma diferente a hastes verticais e a volume foliar.',
      ] },
      { h2: 'Fluxo de trabalho' },
      { steps: [
        'Defina sua AOI e o intervalo de datas.',
        'Escolha a polarização (VV, VH) e as configurações de órbita.',
        'Obtenha a série de retroespalhamento e inspecione o gráfico interativo.',
        'Renderize qualquer data como camada estilizada no mapa ou baixe os dados.',
      ] },
      { h2: 'Filtragem por data & gráficos' },
      { p: 'O módulo lista as aquisições Sentinel-1 disponíveis para sua AOI, permite filtrar por data e plota a evolução do retroespalhamento por polarização. A renderização estilizada aplica uma simbologia pronta, tornando as imagens de radar interpretáveis à primeira vista.' },
      { note: 'Valores SAR são em decibéis (dB) e tipicamente negativos — ex.: −18 dB para solo exposto, −10 dB para dossel denso. A variação relativa no tempo importa mais que os valores absolutos.' },
    ],
  },
  {
    slug: 'dem',
    icon: '⛰️',
    title: 'DEM & Terreno',
    summary: 'Catálogo de elevação, downloads e renderização de terreno.',
    sections: [
      { p: 'O módulo DEM baixa Modelos Digitais de Elevação para qualquer AOI e deriva visualizações de terreno — a camada base para planejamento de drenagem, terraceamento, orientação de máquinas e análise de erosão.' },
      { h2: 'Catálogo de elevação' },
      { p: 'Navegue por um catálogo de conjuntos de elevação globais e regionais (ex.: SRTM, Copernicus DEM e outras fontes hospedadas no GEE), verifique a disponibilidade para sua AOI e escolha a resolução adequada ao seu objetivo.' },
      { h2: 'Download' },
      { p: 'Selecione o conjunto de dados e a AOI, e o módulo baixa um GeoTIFF recortado em segundo plano. A disponibilidade é verificada antes, para você não esperar por uma requisição vazia.' },
      { h2: 'Produtos de terreno' },
      { p: 'Após o download, o FARM tools pode renderizar o DEM como sombreamento (hillshade) e camadas de terreno estilizadas diretamente no QGIS, dando percepção imediata do relevo sem trabalho manual de simbologia.' },
      { note: 'Para microtopografia agrícola (ex.: sistematização com precisão de 1 m) ainda são necessários levantamentos dedicados — DEMs públicos resolvem o macro-relevo (grades de 10–30 m).' },
    ],
  },
  {
    slug: 'sysi',
    icon: '🟤',
    title: 'SYSI Solo Exposto',
    summary: 'Composições sintéticas de solo exposto para mapeamento de solos.',
    sections: [
      { p: 'O SYSI (Synthetic Soil Image) constrói uma composição em que cada pixel mostra a superfície do solo livre de vegetação — mesmo que nenhuma data isolada mostre toda a área exposta. É um insumo-chave para mapeamento digital de solos, delineamento de classes de solo e zonas de manejo.' },
      { h2: 'Como funciona' },
      { steps: [
        'O módulo varre uma pilha multianual de imagens de satélite sobre sua AOI.',
        'Para cada pixel, o método GEOS3 (Geospatial Soil Sensing System) detecta as datas em que aquele pixel estava com solo exposto, usando regras espectrais que separam solo de vegetação, palhada e nuvens.',
        'As observações de solo exposto são combinadas por pixel em uma única composição sintética.',
        'O resultado é renderizado no QGIS e pode ser exportado como GeoTIFF.',
      ] },
      { h2: 'O que fazer com um SYSI' },
      { list: [
        'Delinear classes de solo e transições visualmente — diferenças de cor acompanham textura e matéria orgânica.',
        'Apoiar o plano de amostragem: posicione amostras de solo onde a composição mostra zonas distintas.',
        'Alimentar modelos de mapeamento digital de solos com um preditor espectral estável.',
      ] },
      { note: 'Áreas que nunca ficaram expostas no período analisado (pastagem permanente, floresta) ficam vazias na composição — amplie o intervalo de datas para melhorar a cobertura.' },
    ],
  },
  {
    slug: 'climaplots',
    icon: '🌦️',
    title: 'ClimaPlots',
    summary: 'Séries climáticas NASA POWER e gráficos.',
    sections: [
      { p: 'O ClimaPlots busca séries climáticas do NASA POWER — um conjunto de reanálise global e gratuito — para sua AOI e as plota em gráficos interativos dentro do QGIS. Sem necessidade de estação meteorológica.' },
      { h2: 'Variáveis disponíveis' },
      { list: [
        'Precipitação',
        'Temperatura do ar (mín / máx / média)',
        'Radiação solar',
        'Umidade relativa e velocidade do vento',
      ] },
      { h2: 'Usos típicos' },
      { list: [
        'Explicar anomalias em séries de NDVI — quedas após geada, platôs durante seca.',
        'Comparar a chuva da safra com as médias históricas antes do planejamento.',
        'Documentar o contexto meteorológico em relatórios de campo.',
      ] },
      { p: 'No módulo Óptico, a série climática pode ser sobreposta diretamente ao gráfico de índice de vegetação, alinhando a resposta da cultura com chuva e temperatura no mesmo eixo temporal.' },
      { note: 'As células do NASA POWER têm ~0,5° (≈50 km), representando o clima regional, não o microclima da fazenda. Para variabilidade intra-fazenda use sensores locais.' },
    ],
  },
  {
    slug: 'fieldguide',
    icon: '📍',
    title: 'Guia de Campo',
    summary: 'Captura de pontos, amostragem de polígonos, pontos ótimos por raster, rotas e exportações.',
    sections: [
      { p: 'O Guia de Campo transforma o mapa do QGIS em um planejador de campanhas de campo: capture pontos de amostragem, gere-os automaticamente a partir de talhões (geométrico ou otimizado por raster), abra rotas de carro e exporte a sessão como CSV, GPX, camada QGIS ou relatório PDF para celular.' },
      { p: 'Todos os pontos são armazenados internamente em WGS84 (EPSG:4326), independentemente do CRS do projeto, com precisão de 8 decimais (~1 mm) — as coordenadas atravessam todas as exportações sem perda.' },
      { h2: 'Captura manual & entrada de coordenadas' },
      { list: [
        'Capturar pontos no mapa: cada clique adiciona um marcador numerado. A ferramenta restaura a ferramenta de mapa anterior ao ser desligada e nunca sequestra o canvas permanentemente.',
        'Entrada manual: digite latitude/longitude diretamente. Vírgula e ponto decimais são aceitos (-23,5505 ≡ -23.5505), com validação de intervalo.',
      ] },
      { h2: 'Amostragem de polígonos (geométrica)' },
      { p: 'Gere pontos de amostra para cada feição de uma camada de polígonos. A quantidade é fixa por feição (1–50) ou por densidade (uma marca a cada N hectares, medidos elipsoidalmente). Métodos de distribuição:' },
      { list: [
        'Centroide — um ponto no centroide do polígono; rápido para talhões compactos.',
        'Distribuição otimizada (padrão) — seleção maximin gulosa que aproxima um desenho de preenchimento de espaço, robusta em formas irregulares; saída ordenada para um caminhamento estável.',
        'Grade sistemática — grade alinhada ao eixo longo do talhão (via PCA da nuvem de candidatos), não ao norte do mapa.',
        'Transecto em zigue-zague — o clássico caminhamento serpentina de amostragem de solo ao longo do eixo maior do talhão.',
      ] },
      { p: 'Os pontos são mantidos longe das bordas por um buffer interno automático (3–12% do tamanho do talhão), evitando efeitos de borda como pixels misturados e cabeceiras de máquina. A amostragem é determinística: mesma camada, método e quantidade sempre produzem os mesmos pontos — planos reproduzíveis e auditáveis.' },
      { h2: 'Pontos ótimos baseados em raster' },
      { p: 'Em vez de posicionamento geométrico, deixe os dados decidirem: um ponto por polígono no local de valor máximo do raster (ex.: pico de uma composição NDVI), para que a equipe de campo visite o ponto mais representativo fisiologicamente de cada talhão.' },
      { steps: [
        'Habilite "Usar seleção de ponto ótimo baseada em raster".',
        'Escolha a camada raster e a banda.',
        'Os pontos são calculados imediatamente — o polígono é reprojetado para o CRS do raster (o raster nunca é reamostrado), mascarado pela geometria exata, limpo de no-data e ruído de borda, e o máximo suavizado é selecionado.',
      ] },
      { p: 'Casos extremos são tratados explicitamente: polígonos totalmente nublados são pulados e contabilizados, polígonos sub-pixel são sinalizados, e basemaps web (XYZ, WMS) são rejeitados de antemão por não terem grade de pixels legível. Nome do raster, banda, CRS e o valor em cada ponto acompanham todas as exportações, garantindo rastreabilidade total.' },
      { h2: 'Rotas (Google Maps)' },
      { p: 'Abra os pontos da sessão como rota de carro ordenada no Google Maps. Sessões longas são divididas em segmentos de 10 pontos com sobreposição de 1 ponto, mantendo a continuidade em rotas multissegmento.' },
      { h2: 'Exportações' },
      { table: {
        headers: ['Formato', 'Conteúdo'],
        rows: [
          ['CSV', 'ordem, longitude, latitude (8 decimais); colunas de fonte do raster, método e valor quando a seleção por raster foi usada'],
          ['GPX', 'Waypoints FG001…FGnnn (compatíveis com GPS de mão) mais uma rota ordenada; metadados do raster nas descrições'],
          ['Camada temporária', 'Camada de pontos em memória no CRS do projeto com atributos ordem/nome/lon/lat'],
          ['Relatório PDF', 'Captura do mapa mais um cartão por ponto com link para o Google Maps; rodapé com a metodologia do raster quando aplicável'],
        ],
      } },
      { h2: 'Gerenciamento da sessão' },
      { list: [
        'Lista de pontos ao vivo com contagem e prontidão de rota.',
        'Remover último, excluir selecionado (numeração permanece contígua) e limpar com confirmação.',
        'Aviso Anexar / Substituir protege o trabalho existente ao gerar ou importar em uma sessão não vazia.',
        'Importação CSV: exige cabeçalhos longitude/latitude (qualquer ordem, sem distinção de maiúsculas), aceita vírgula decimal e informa as linhas puladas.',
      ] },
    ],
  },
  {
    slug: 'mapbiomas',
    icon: '🗺️',
    title: 'MapBiomas',
    summary: 'Uso e cobertura da terra do Brasil por ano e análise configurável de transições.',
    sections: [
      { p: 'O MapBiomas traz o acervo anual de uso e cobertura da terra da Coleção 9 do MapBiomas Brasil para o QGIS. Explore qualquer ano dentro do módulo, baixe um ano para o QGIS como raster de classificação estilizado, ou analise como a terra mudou ao longo do tempo. A cobertura é apenas do Brasil e usa o Google Earth Engine.' },
      { h2: 'Cobertura' },
      { list: [
        'Explore todos os anos (1985–2023) no módulo com um controle deslizante de ano, ao lado da legenda oficial de 63 classes.',
        'Baixe qualquer ano para o QGIS como um raster de classificação de banda única estilizado com a paleta oficial do MapBiomas — IDs de classe reais, mantendo os pixels consultáveis e analisáveis.',
      ] },
      { h2: 'Análise de transição' },
      { p: 'Mapeie o primeiro ano em que cada pixel mudou de um uso de origem para um uso de destino, e visualize a área convertida por ano.' },
      { list: [
        'Predefinições: Pastagem → Lavoura, Desmatamento (floresta → antrópico), Regeneração florestal, Expansão agrícola e Expansão urbana.',
        'Personalizado: escolha qualquer combinação de classes de origem e destino.',
        'Um controle de intervalo de anos filtra o gráfico em tempo real e limita a camada de transição exportada, que carrega no QGIS classificada por ano de transição.',
      ] },
      { note: 'A Coleção 9 do MapBiomas cobre apenas o Brasil — áreas fora do Brasil retornam resultados vazios. Requer autenticação no Google Earth Engine, como os demais módulos GEE.' },
    ],
  },
  {
    slug: 'exports-downloads',
    icon: '💾',
    title: 'Exportações & Downloads',
    summary: 'Formatos de saída de todos os módulos e onde os arquivos são salvos.',
    sections: [
      { p: 'Todos os módulos do FARM tools produzem formatos padrão e portáveis, que abrem no QGIS e além.' },
      { table: {
        headers: ['Módulo', 'Saídas'],
        rows: [
          ['Óptico', 'Séries de índices (gráfico + CSV), imagens e composições GeoTIFF, download multiespectral em lote'],
          ['Landsat', 'Séries temporais, cenas GeoTIFF, downloads em lote e super-resolução'],
          ['SAR', 'Séries e gráficos de retroespalhamento, camadas raster estilizadas, download GeoTIFF'],
          ['DEM', 'Elevação GeoTIFF recortada, renderização hillshade/terreno'],
          ['SYSI', 'Composição sintética de solo exposto como camada renderizada / GeoTIFF'],
          ['ClimaPlots', 'Gráficos e dados de séries climáticas'],
          ['Guia de Campo', 'CSV, GPX, camada temporária QGIS, relatório PDF, rotas Google Maps'],
          ['MapBiomas', 'GeoTIFF de classificação por ano e GeoTIFF de transição (classificado por ano de transição), camadas estilizadas por paleta'],
        ],
      } },
      { h2: 'Pasta de download & proxy' },
      { p: 'A pasta padrão de download e um proxy HTTP(S) opcional são configurados nas preferências do plugin e persistem entre sessões. Todos os downloads pesados rodam em segundo plano — você pode continuar trabalhando no QGIS enquanto concluem.' },
    ],
  },
  {
    slug: 'faq',
    icon: '❓',
    title: 'FAQ & Solução de Problemas',
    summary: 'Problemas comuns: autenticação, dependências, proxies e convivência com o RAVI.',
    sections: [
      { h2: 'A autenticação falha ou pede login toda sessão' },
      { list: [
        'Confirme que a Earth Engine API está habilitada no seu projeto Cloud (Console Cloud → APIs).',
        'Confirme que o ID informado é o ID do projeto Cloud, não o nome do projeto.',
        'O OAuth pessoal abre uma janela do navegador — se ela nunca aparecer, verifique seu navegador padrão e bloqueadores de popup.',
        'Para contas de serviço: o caminho da chave JSON deve ser legível e a conta de serviço deve estar registrada para uso do Earth Engine.',
      ] },
      { h2: 'Problemas na instalação de dependências' },
      { list: [
        'O primeiro carregamento baixa um pacote de dependências pré-compilado para a sua versão de Python do QGIS; em caso de falha, usa o pip. Ambos precisam de internet.',
        'Atrás de firewall corporativo, configure a URL do proxy nas preferências do plugin e reinicie o QGIS.',
        'Após atualizar o QGIS (nova versão de Python), as dependências são reprovisionadas automaticamente no próximo carregamento.',
      ] },
      { h2: 'Gráficos ou downloads vêm vazios' },
      { list: [
        'Verifique se a AOI realmente intersecta imagens disponíveis no intervalo de datas selecionado.',
        'No Sentinel-2, um limite de nuvens muito rígido pode filtrar todas as cenas — relaxe o limite e tente de novo.',
        'O GEE tem cotas de uso; AOIs muito grandes ou períodos longos podem precisar ser divididos.',
      ] },
      { h2: 'Posso usar o FARM tools junto com o RAVI?' },
      { p: 'Sim. O FARM tools é um fork do plugin RAVI com identidade própria (pasta, menu, barra de ferramentas) e foi projetado para conviver com o RAVI no mesmo perfil do QGIS. O login no GEE e as preferências de download são compartilhados de propósito, então uma configuração existente do RAVI é aproveitada.' },
      { h2: 'Quais versões do QGIS são suportadas?' },
      { p: 'QGIS 3.28 ou mais recente (Python 3.11–3.13). O QGIS 3.44 LTR com Python 3.12 é a plataforma de referência.' },
      { h2: 'Onde reporto bugs ou peço funcionalidades?' },
      { p: 'Abra uma issue em github.com/farmanalytica/farm_tools/issues. Para suporte comercial e soluções personalizadas, fale com a FARM Analytica pelo WhatsApp ou adm@farmanalytica.com.br.' },
    ],
  },
]
