// Wiki articles — English. Section types: h2, p, list, steps, table, note.
export default [
  {
    slug: 'getting-started',
    icon: '🚀',
    title: 'Getting Started',
    summary: 'Install the plugin, set up Google Earth Engine, and authenticate.',
    sections: [
      { p: 'FARM tools is a QGIS plugin powered by Google Earth Engine (GEE). Before using any module you need QGIS 3.28 or newer, a free GEE account, and a Google Cloud project with the Earth Engine API enabled.' },
      { h2: 'Installation' },
      { steps: [
        'Open QGIS and go to Plugins → Manage and Install Plugins.',
        'Search for "FARM tools" and click Install.',
        'On first activation the plugin automatically downloads its dependency bundle (earthengine-api, agrigee-lite, and related packages). If the download fails it falls back to pip; just wait for the loading page to finish.',
      ] },
      { note: 'Dependencies are installed into the plugin\'s own extlibs folder and never shadow the packages shipped with QGIS (numpy, pandas, etc.). A QGIS/Python upgrade re-provisions them automatically.' },
      { h2: 'Google Earth Engine setup' },
      { steps: [
        'Create a free GEE account at earthengine.google.com/signup.',
        'Create a Google Cloud project at console.cloud.google.com and link it to your GEE account.',
        'In the Cloud Console, search for "Earth Engine API" and enable it.',
        'Open the Earth Engine Code Editor (code.earthengine.google.com) to find your project ID.',
        'In QGIS, open FARM tools, click Setup Authentication, enter the project ID, and authorize access in the browser window that opens.',
      ] },
      { h2: 'Authentication modes' },
      { p: 'FARM tools supports two ways of signing in to Earth Engine:' },
      { list: [
        'Personal OAuth — sign in with your Google account in the browser. Recommended for individual users.',
        'Service account — point the plugin to a service-account JSON key file. Recommended for shared machines, automation, or institutional accounts.',
      ] },
      { h2: 'Defining an area of interest (AOI)' },
      { p: 'Every module starts from an AOI. You can draw a polygon directly on the QGIS canvas with the built-in AOI tool, or select an existing vector layer. The AOI is converted to a WGS84 Earth Engine geometry internally, so any project CRS works.' },
      { note: 'If you previously used the RAVI plugin, your GEE project ID, auth mode, and download preferences carry over automatically — FARM tools shares those settings keys.' },
    ],
  },
  {
    slug: 'optical',
    icon: '🌿',
    title: 'Optical (Sentinel-2)',
    summary: 'Vegetation index time series, cloud filtering, composites, and multispectral download.',
    sections: [
      { p: 'The Optical module works with the harmonized Sentinel-2 surface-reflectance archive (COPERNICUS/S2_SR_HARMONIZED): 10 m resolution, ~5-day revisit, 12 usable spectral bands plus the SCL quality band. It is the workhorse for crop and vegetation monitoring. All processing runs server-side on Google Earth Engine, so no archive download is needed.' },
      { h2: 'Vegetation index time series' },
      { p: 'Build a time series of a chosen spectral index over your AOI for any date range. Because an AOI near a tile edge can return more than one image per date, the module keeps exactly one scene per date (scored by AOI footprint coverage, with tile cloudiness as tie-breaker), then averages the index over the AOI at 10 m for each kept date.' },
      { p: 'Nineteen indices are built in, grouped by what they measure:' },
      { list: [
        'Greenness / vigour — NDVI, GNDVI, EVI, EVI2, SAVI, MSAVI, ARVI, VARI, TVI, SFDVI.',
        'Chlorophyll / red-edge — CIgreen, NDRE, ReCI, MTCI, MCARI, SIPI.',
        'Water, moisture & burn — NDMI, NDWI, NBR.',
        'Custom — define your own band expression (e.g. (B8 - B4) / (B8 + B4 + 0.5)); it is validated for safety and saved for reuse.',
      ] },
      { note: 'No single index is best for everything: NDVI saturates over dense canopy (prefer EVI/EVI2 or red-edge indices), soil-adjusted indices (SAVI/MSAVI) suit sparse cover, and red-edge/chlorophyll indices track nitrogen and chlorophyll.' },
      { h2: 'Cloud masking (SCL)' },
      { p: 'Cloudy observations distort time series. FARM tools uses the Sentinel-2 Scene Classification Layer (SCL) to mask clouds, shadows, defects, and cirrus before the index is computed. The exact masking is fixed at the start of an analysis and replayed identically for the chart, point/feature sampling, and composites, so every product describes the same clear-sky pixels.' },
      { h2: 'Quality screening & smoothing' },
      { p: 'Each date carries quality metadata: tile cloudiness, the in-AOI valid-pixel percentage (the most reliable flag, measured at 10 m inside your AOI), and AOI footprint coverage. Once the series is computed you can re-screen it by these thresholds or toggle individual dates on and off, and the plot updates instantly — no recomputation. An optional Savitzky-Golay filter de-noises the curve, preserving the timing and amplitude of seasonal peaks.' },
      { h2: 'Point & per-feature sampling' },
      { p: 'Beyond the AOI average, click a location to extract the single 10 m pixel under it (truer to a ground sample than a buffered mean), or compute a mean series for each polygon feature labelled by an attribute field — to compare fields or management zones. Every per-geometry curve is plotted against the AOI-average reference line, reusing the same date range, index, and masking.' },
      { h2: 'Single-date imagery' },
      { p: 'Render any date into QGIS, clipped to the AOI (optionally buffered ±300 m) and exported as 10 m GeoTIFF in EPSG:4326: an RGB / false-colour composite (true colour, NIR or SWIR presets, 2–98% stretch), or the chosen index as a continuous pseudocolour raster.' },
      { h2: 'Composites & Area-Under-Curve' },
      { p: 'Collapse the displayed dates into one map by a chosen statistic — mean, median, min, max, amplitude (max − min), standard deviation, sum, or Area Under Curve (AUC). AUC integrates the index over time with the trapezoidal rule and is a robust proxy for cumulative productivity or biomass over the season.' },
      { h2: 'Multispectral download' },
      { p: 'Batch-download the full multispectral stack (or selected bands) for your AOI as GeoTIFF, for one or many dates. Downloads run on a background thread, so QGIS stays responsive.' },
      { h2: 'Climate overlay' },
      { p: 'Optionally overlay NASA POWER monthly precipitation as bars beneath the vegetation curve to interpret index dynamics against weather events — see the ClimaPlots article.' },
    ],
  },
  {
    slug: 'landsat',
    icon: '🛰️',
    title: 'Landsat',
    summary: 'Decades-long time series and imagery for historical monitoring.',
    sections: [
      { p: 'The Landsat module reaches back to 1999 — Landsat 7, 8, and 9 (USGS Collection 2, Tier 1) — making it the right choice for historical land-use analysis, long-term crop performance, and change detection beyond the Sentinel era (2015+). Landsat 5 is deliberately excluded because its TM sensor carries no panchromatic band, so the 15 m pan-sharpened product cannot be built from it.' },
      { h2: 'Look at TOA, measure on SR' },
      { p: 'Two physically different products are used, each for the job it suits best. The sharp 15 m true-colour image is built from Top-of-Atmosphere (TOA) reflectance, where spatial detail matters more than absolute calibration; all quantitative indices and composites are computed on atmospherically-corrected Surface Reflectance (SR) at 30 m.' },
      { h2: '15 m pan-sharpened true colour' },
      { p: 'HSV pan-sharpening doubles the apparent detail of the true-colour image: the 30 m RGB is converted to Hue–Saturation–Value, the 15 m panchromatic band replaces the brightness (value) channel, and the result is converted back to RGB — taking its colour from the 30 m bands and its detail from the 15 m pan band. Ideal for delineating field boundaries, tracks, and small features.' },
      { h2: 'Spectral indices & composites' },
      { p: 'Fourteen Surface-Reflectance indices are offered (none require a red-edge band, which Landsat lacks): greenness — NDVI, GNDVI, EVI, EVI2; soil-adjusted — SAVI, OSAVI, MSAVI; atmosphere/chlorophyll — ARVI, CIgreen, CIred, MCARI; water and bare soil — NDWI (NIR–SWIR1), MNDWI, BSI. For qualitative interpretation, four band combinations are provided: real colour, colour-infrared (NIR·Red·Green), SWIR1·NIR·Red, and SWIR2·NIR·Green.' },
      { h2: 'Long-term time series (SITS)' },
      { p: 'A Satellite Image Time Series of the chosen index is built across the full archive, reduced over the AOI by the spatial median (default; mean available). Each mission is queried within its own lifespan and the Landsat 7/8/9 series are merged into one chronological record, colour-coded by mission, giving a continuous index history from 1999 to the present.' },
      { h2: 'Scene discovery & download' },
      { p: 'Scenes are cloud-masked (QA_PIXEL bitmask everywhere, plus a Simple Cloud Score pass on TOA) and kept only if they pass a minimum-valid-coverage filter (default 80% of clear, in-AOI pixels) — so you are never shown a date that is mostly cloud or off-frame. Preview surviving dates on the canvas and download as GeoTIFF; powered by agrigee-lite, the module also supports batch download and super-resolution downloads.' },
      { note: 'Landsat revisit (16 days per satellite, ~8 days for L8+L9 combined) and 30 m resolution make it coarser than Sentinel-2 — prefer the Optical module for current-season monitoring and Landsat for history. The Landsat 7 scan-line corrector failed in 2003, leaving striped gaps; prefer Landsat 8/9 for gapless post-2013 work.' },
    ],
  },
  {
    slug: 'sar',
    icon: '📡',
    title: 'SAR (Sentinel-1)',
    summary: 'Cloud-independent radar backscatter analysis for all-weather monitoring.',
    sections: [
      { p: 'Synthetic Aperture Radar (SAR) actively illuminates the ground with microwaves and measures the returned signal (backscatter). Unlike optical sensors, it works through clouds, smoke, and at night — essential during rainy seasons when optical series have gaps.' },
      { h2: 'What backscatter tells you' },
      { list: [
        'Surface roughness — tilled soil, growing canopy, and harvested fields return distinct signatures.',
        'Moisture — wet soil and vegetation reflect more strongly, useful for irrigation and flood monitoring.',
        'Structure — VV and VH polarizations respond differently to vertical stems versus leafy volume.',
      ] },
      { h2: 'Analysis-Ready Data pipeline' },
      { p: 'Raw Ground Range Detected (GRD) scenes in Interferometric Wide swath are standardized following the Mullissa et al. (2021) Sentinel-1 ARD framework, with three independently switchable corrections (all on by default):' },
      { list: [
        'Border-noise removal — discards the noisy scene margins (incidence angles outside ~30.6°–45.2°).',
        'Speckle filtering — a multi-temporal Gamma-MAP filter suppresses the grainy speckle while preserving edges (Lee, Refined Lee, Lee-Sigma, Boxcar also available).',
        'Radiometric terrain flattening — normalizes backscatter to terrain-flattened gamma-naught (γ⁰) using a DEM, so identical cover looks the same on flat and sloped ground.',
      ] },
      { p: 'The orbit is fixed to the descending pass so every observation in a series shares one viewing geometry. Output is delivered in decibels (dB) by default, or linear power.' },
      { h2: 'Dual-polarization indices' },
      { p: 'From VV and VH, nine radar indices are derived — VV/VH Ratio, RVI, DpRVI, CR, NDPI, PD, DPSVIm, PRVI, and mRVI. The vegetation-oriented ones (RVI, DpRVI, mRVI, PRVI) trend upward through the growing season as the canopy depolarizes the signal — a radar analogue of an NDVI growth curve, unbroken by cloud — while difference/ratio indices track the shift between bare, vegetated, and harvested regimes.' },
      { h2: 'Time series, composites & rendering' },
      { p: 'The AOI-mean of any index (or raw VV/VH) is plotted as a dense, weather-independent time series. Beyond that, export a single date (VV, VH, and all nine indices) or a composite reduced by mean, median, min, max, amplitude, standard deviation, sum, or AUC. Images render two ways: an RGB composite (qualitative — colour reveals land-cover contrasts) or single-band pseudocolour (quantitative — each colour maps to a value on a legend).' },
      { note: 'SAR values are in decibels (dB) and typically negative — e.g. ≈ −20 dB or below for smooth/dry surfaces and open water, −15 to −8 dB for vegetation, higher for urban or wet/flooded targets. Backscatter rises with surface moisture too, so a sudden brightening can be rain or irrigation, not growth. Relative change over time matters more than absolute values; favour area statistics over single pixels.' },
    ],
  },
  {
    slug: 'dem',
    icon: '⛰️',
    title: 'DEM & Terrain',
    summary: 'Elevation catalog browsing, AOI-aware downloads, and Magma rendering.',
    sections: [
      { p: 'The DEM module delivers ready-to-use elevation data for any AOI from a curated catalog of roughly thirty public Digital Elevation Models — from global radar/optical products to sub-metre national LiDAR — as the base surface for drainage planning, terracing, machine guidance, and erosion analysis.' },
      { p: 'A key distinction runs through the catalog: a Digital Terrain Model (DTM) is the bare earth (vegetation and buildings removed — best for hydrology and ground analysis), while a Digital Surface Model (DSM) is the top of the surface, including canopy and rooftops.' },
      { h2: 'Elevation catalog' },
      { p: 'Browse global products (Copernicus GLO-30, NASADEM, SRTM, ALOS AW3D30, ASTER, MERIT…) and regional/national LiDAR (USGS 3DEP, Netherlands AHN, England, France RGE ALTI, Australia, ArcticDEM/REMA…). For most land work the 30 m global products are the practical default; choose national LiDAR for accuracy where it covers the AOI, MERIT/DEM-H for hydrological consistency, and the polar models for ice and high latitudes.' },
      { h2: 'AOI-aware availability' },
      { p: 'Once an AOI is set, the catalog is filtered so only datasets that actually cover it are offered: a fast bounding-box screen rules out non-overlapping regional products, then a live Earth Engine check confirms real pixels exist within the AOI. The result is a short, trustworthy list. (Without GEE sign-in, the live check is skipped and the full catalog is shown for browsing.)' },
      { h2: 'Clip, buffer & export' },
      { p: 'Optionally buffer the AOI from −300 m to +300 m, then the model is masked to the AOI (pixels outside become transparent no-data) and exported as a floating-point GeoTIFF in EPSG:4326. Export is at a fixed 30 m grid regardless of native resolution — so a 0.5 m or 1 m LiDAR source is resampled down to 30 m on export; the fine national models are valuable here for accuracy and bare-earth quality, not delivered detail.' },
      { h2: 'Rendering' },
      { p: 'The downloaded raster is styled as a single-band pseudocolour layer using the perceptually-uniform Magma ramp, stretched between the AOI’s local min and max elevation — so colours are relative to the area shown. Read the value range to anchor colours to real heights.' },
      { note: 'The module delivers the raw elevation surface only — it does not compute slope, aspect, hillshade, contours, or flow direction. Generate those in QGIS from the downloaded raster so the method and parameters stay explicit. Vertical datums differ between products, so heights are not directly comparable without reduction to a common reference.' },
    ],
  },
  {
    slug: 'sysi',
    icon: '🟤',
    title: 'SYSI Bare Soil',
    summary: 'Synthetic bare-soil image composites for soil mapping.',
    sections: [
      { p: 'SYSI (Synthetic Soil Image) builds a composite where every pixel shows the soil surface free of vegetation — even though no single date shows the whole area bare. Built from the harmonized Sentinel-2 surface-reflectance archive (2017 onward) at 10 m, it is a key input for digital soil mapping, soil-class delineation, and management zones. The bare-soil rule follows the GEOS3 method of Demattê et al. (2018).' },
      { h2: 'How it works' },
      { steps: [
        'You set the AOI, a date range, the calendar months to include, a maximum cloud cover, and the NDVI/NBR2 threshold ranges.',
        'Each scene is cloud-screened (QA60), then four diagnostic quantities are computed per pixel: NDVI, NBR2, and the visible-slope terms.',
        'A pixel is kept as bare soil only when all five GEOS3 conditions hold — low NDVI (removes green vegetation), NBR2 in range (removes dry straw/residue), a soil-like spectral shape, and a rising blue→green→red visible slope.',
        'The surviving bare observations are collapsed per pixel by the temporal median, which is robust to outliers and naturally fills gaps from dates when each pixel happened to be bare.',
        'The result is a 9-band, 10 m image (Blue, Green, Red, Red-edge 2, NIR, SWIR1, SWIR2, NDVI, NBR2), rendered in QGIS and exportable as GeoTIFF.',
      ] },
      { note: 'Restrict the months to the local fallow/tillage season so soil is most likely exposed. Permissive NDVI/NBR2 ranges admit sparse vegetation or residue; strict ranges discard valid soil and shrink coverage.' },
      { h2: 'What you can do with a SYSI' },
      { list: [
        'Delineate soil classes and transitions visually — color differences track texture and organic matter.',
        'Support sampling design: place soil samples where the composite shows distinct zones.',
        'Feed digital soil mapping models with a stable spectral predictor.',
      ] },
      { note: 'Areas that were never bare during the analyzed period (permanent pasture, forest) stay empty in the composite — extend the date range to improve coverage.' },
    ],
  },
  {
    slug: 'climaplots',
    icon: '🌦️',
    title: 'ClimaPlots',
    summary: 'Climate diagnosis for any point: trends, climate diagram, extreme indices, and drought (SPI).',
    sections: [
      { p: 'ClimaPlots turns decades of daily gridded climate data for a point you click (or type) into a compact climate diagnosis — long-term trends, the average seasonal regime, standardized climate-extreme indices, and a drought index. It needs no GEE account and no weather station; the data are free and globally consistent.' },
      { h2: 'Two interchangeable datasets' },
      { list: [
        'NASA POWER — bias-corrected satellite/model daily meteorology, global, 1981 → present (~0.5°).',
        'ERA5 / ERA5-Land reanalysis (via Open-Meteo) — gap-free physically consistent record, global, 1940 → present (~0.25°/0.1°).',
      ] },
      { p: 'You can overlay a second point B that may even use the other source, so the same location can be compared across both datasets. Both are harmonized to a common set of variables and units: max/min temperature (°C), precipitation (mm/day), relative humidity (%), irradiation (kWh/m²/day), and wind speed (m/s).' },
      { h2: 'Derived agronomic variables' },
      { p: 'Two variables are computed from temperature: Growing Degree Days (accumulated heat above a 10 °C base) and reference evapotranspiration ET0 (atmospheric water demand). ET0 uses the temperature-based Hargreaves equation for POWER, while Open-Meteo supplies its own FAO-56 Penman–Monteith ET0 directly.' },
      { h2: 'Annual trends & statistics' },
      { p: 'Each annual series (sums for precipitation, ET0, GDD; means for the rest) is tested with two non-parametric tests at α = 0.05: the Mann–Kendall trend test (increasing / decreasing / no trend, with a p-value) and the Pettitt change-point test (homogeneous, or a probable break year). Both verdicts are reported in the chart title.' },
      { h2: 'Thermo-pluviometric diagram' },
      { p: 'A Walter–Lieth style diagram of the average yearly cycle — twelve mean monthly rainfall bars with mean monthly max/min temperature lines on a secondary axis — to identify wet and dry seasons and likely water-deficit periods.' },
      { h2: 'ETCCDI extreme indices' },
      { p: 'A standardized panel of WMO climate-change indices computed from daily data: frost days, tropical nights, icing days, summer days; monthly TXx/TXn and TNx/TNn and daily temperature range; and for precipitation Rx1day/Rx5day, R10mm/R20mm, SDII, and consecutive dry/wet days (CDD/CWD).' },
      { h2: 'Standardized Precipitation Index (SPI)' },
      { p: 'A 90-day SPI expresses rainfall as a gamma-fitted statistical anomaly in standard-deviation units, comparable across climates: sustained negative excursions mark droughts, positive ones wet periods (|SPI| ≥ 2 is extreme).' },
      { h2: 'Typical uses' },
      { list: [
        'Explain anomalies in NDVI series — drops after frost, plateaus during drought.',
        'Assess recent climatic change at a farm, trial site, or watershed.',
        'Document weather context in field reports; in the Optical module the rainfall series can be overlaid on the vegetation chart.',
      ] },
      { note: 'Values are gridded, not station data — sharp topographic/coastal microclimates are smoothed out. POWER and ERA5 differ in method, resolution, and start year, so the same point can yield somewhat different values or trends; comparing them via point B is informative. Trend results depend on the chosen window — prefer the longest defensible period.' },
    ],
  },
  {
    slug: 'fieldguide',
    icon: '📍',
    title: 'Field Guide',
    summary: 'Field point capture, polygon sampling, raster-optimal points, routes, and exports.',
    sections: [
      { p: 'Field Guide turns the QGIS canvas into a field-campaign planner: capture sampling points, generate them automatically from polygon parcels (geometric or raster-optimized), open driving routes, and export the session as CSV, GPX, a QGIS layer, or a phone-friendly PDF report.' },
      { p: 'All points are stored internally in WGS84 (EPSG:4326) regardless of the project CRS, with 8-decimal precision (~1 mm) — coordinates round-trip losslessly through every export.' },
      { h2: 'Manual capture & coordinate entry' },
      { list: [
        'Capture points on map: each canvas click adds a numbered marker. The tool restores the previous map tool when toggled off and never permanently hijacks the canvas.',
        'Manual entry: type latitude/longitude directly. Both dot and comma decimals are accepted (-23,5505 ≡ -23.5505), with range validation.',
      ] },
      { h2: 'Polygon sampling (geometric)' },
      { p: 'Generate sample points for every feature of a polygon layer. Quantity is either a fixed count per feature (1–50) or a density (one mark per N hectares, measured ellipsoidally). Distribution methods:' },
      { list: [
        'Centroid — one point at the polygon centroid; fast for compact parcels.',
        'Spread optimized (default) — greedy maximin selection approximating a space-filling design, robust on irregular shapes; output sorted for a stable walking order.',
        'Systematic grid — a grid aligned with the parcel\'s long axis (via PCA of the candidate cloud), not with map north.',
        'Zigzag transect — the classic serpentine soil-sampling walk along the parcel\'s major axis.',
      ] },
      { p: 'Points are kept away from parcel borders by an automatic inward buffer (3–12% of the parcel size), avoiding edge effects like mixed pixels and machinery turn rows. Sampling is deterministic: the same layer, method, and count always produce the same points, so plans are reproducible and auditable.' },
      { h2: 'Raster-based optimal points' },
      { p: 'Instead of geometric placement, let the data decide: one point per polygon at the location of the maximum raster value (e.g. an NDVI composite peak), so field workers visit the most physiologically representative spot of each parcel.' },
      { steps: [
        'Enable "Use raster-based optimal point selection".',
        'Pick the raster layer and band.',
        'Points are computed immediately — the polygon is reprojected to the raster CRS (the raster is never resampled), masked to the exact geometry, cleaned of no-data and edge noise, and the smoothed maximum is selected.',
      ] },
      { p: 'Edge cases are handled explicitly: fully clouded polygons are skipped and counted, sub-pixel polygons are flagged, and web/tile basemaps (XYZ, WMS) are rejected up front since they have no readable pixel grid. Raster name, band, CRS, and the value at each point flow into every export for full traceability.' },
      { h2: 'Routes (Google Maps)' },
      { p: 'Open the session points as an ordered driving route in Google Maps. Long sessions are split into 10-point segments with a 1-point overlap, so multi-segment routes stay continuous.' },
      { h2: 'Exports' },
      { table: {
        headers: ['Format', 'Contents'],
        rows: [
          ['CSV', 'order, longitude, latitude (8 decimals); raster source, method, and value columns when raster selection was used'],
          ['GPX', 'Waypoints FG001…FGnnn (GPS-handheld friendly) plus an ordered route; raster metadata in waypoint descriptions'],
          ['Temporary layer', 'In-memory point layer in the project CRS with order/name/lon/lat attributes'],
          ['PDF report', 'Canvas snapshot plus one tap-target card per point linking to Google Maps; raster methodology footer when applicable'],
        ],
      } },
      { h2: 'Session management' },
      { list: [
        'Live point list with count and route readiness.',
        'Remove last, delete selected (numbering stays contiguous), and clear with confirmation.',
        'Append / Replace prompt protects existing work when generating or importing into a non-empty session.',
        'CSV import: requires longitude/latitude headers (any order, case-insensitive), accepts comma decimals, reports skipped rows.',
      ] },
    ],
  },
  {
    slug: 'mapbiomas',
    icon: '🗺️',
    title: 'MapBiomas',
    summary: 'Brazilian land-use/land-cover by year and configurable transition analysis.',
    sections: [
      { p: 'MapBiomas brings the MapBiomas Brasil Collection 9 annual land-use / land-cover archive into QGIS. Browse any year inside the module, download a year to QGIS as a styled classification raster, or analyze how the land changed over time. Coverage is Brazil-only and runs through Google Earth Engine.' },
      { h2: 'Coverage' },
      { list: [
        'Browse every year (1985–2023) in-module with a year slider, beside the official 63-class legend.',
        'Download any single year to QGIS as a single-band classification raster styled with the official MapBiomas palette — real class IDs, so pixels stay queryable and analyzable.',
      ] },
      { h2: 'Transition analysis' },
      { p: 'Map the first year each pixel changed from a source land-use to a target land-use, and chart the converted area per year.' },
      { list: [
        'Presets: Pasture → Crop, Deforestation (forest → anthropic), Forest regrowth, Agricultural expansion, and Urban expansion.',
        'Custom: pick any combination of source and target classes.',
        'A year-range slider filters the chart live and limits the exported transition layer, which loads into QGIS classed by transition year.',
      ] },
      { note: 'MapBiomas Collection 9 covers Brazil only — areas outside Brazil return empty results. Requires Google Earth Engine authentication, like the other GEE modules.' },
    ],
  },
  {
    slug: 'exports-downloads',
    icon: '💾',
    title: 'Exports & Downloads',
    summary: 'Output formats across all modules and where files are saved.',
    sections: [
      { p: 'Every FARM tools module produces standard, portable formats that open in QGIS and beyond.' },
      { table: {
        headers: ['Module', 'Outputs'],
        rows: [
          ['Optical', 'Index time series (chart + CSV), GeoTIFF imagery and composites, multispectral batch download'],
          ['Landsat', 'Time series, GeoTIFF scenes, batch and super-resolution downloads'],
          ['SAR', 'Backscatter series and plots, styled raster layers, GeoTIFF download'],
          ['DEM', 'Clipped GeoTIFF elevation, hillshade/terrain rendering'],
          ['SYSI', 'Synthetic bare-soil composite as a rendered layer / GeoTIFF'],
          ['ClimaPlots', 'Climate series charts and data'],
          ['Field Guide', 'CSV, GPX, temporary QGIS layer, PDF report, Google Maps routes'],
          ['MapBiomas', 'Classification GeoTIFF per year and transition GeoTIFF (classed by transition year), styled paletted layers'],
        ],
      } },
      { h2: 'Download folder & proxy' },
      { p: 'The default download folder and an optional HTTP(S) proxy are configured in the plugin settings and persist across sessions. All heavy downloads run on background threads — you can keep working in QGIS while they complete.' },
    ],
  },
  {
    slug: 'faq',
    icon: '❓',
    title: 'FAQ & Troubleshooting',
    summary: 'Common problems: authentication, dependencies, proxies, and coexistence with RAVI.',
    sections: [
      { h2: 'Authentication fails or asks again every session' },
      { list: [
        'Confirm the Earth Engine API is enabled for your Cloud project (Cloud Console → APIs).',
        'Confirm the project ID is the Cloud project ID, not the project name.',
        'Personal OAuth opens a browser window — if it never appears, check your default browser and any popup blockers.',
        'For service accounts: the JSON key path must be readable and the service account must be registered for Earth Engine use.',
      ] },
      { h2: 'Dependency installation problems' },
      { list: [
        'First launch downloads a prebuilt dependency bundle matched to your QGIS Python version; on failure it falls back to pip. Both need internet access.',
        'Behind a corporate firewall, set the proxy URL in the plugin settings and restart QGIS.',
        'After a QGIS upgrade (new Python version) dependencies are re-provisioned automatically on next launch.',
      ] },
      { h2: 'Charts or downloads stay empty' },
      { list: [
        'Check the AOI actually intersects available imagery for the selected date range.',
        'For Sentinel-2, a strict cloud threshold can filter out every scene — relax it and retry.',
        'GEE has usage quotas; very large AOIs or long ranges may need to be split.',
      ] },
      { h2: 'Can I run FARM tools next to RAVI?' },
      { p: 'Yes. FARM tools is a fork of the RAVI plugin with its own identity (folder, menu, toolbar) and is designed to run side-by-side with RAVI in the same QGIS profile. GEE sign-in and download preferences are intentionally shared, so an existing RAVI setup carries over.' },
      { h2: 'Which QGIS versions are supported?' },
      { p: 'QGIS 3.28 or newer (Python 3.11–3.13). The QGIS 3.44 LTR with Python 3.12 is the reference platform.' },
      { h2: 'Where do I report bugs or ask for features?' },
      { p: 'Open an issue at github.com/farmanalytica/farm_tools/issues. For commercial support and custom solutions, contact FARM Analytica via WhatsApp or adm@farmanalytica.com.br.' },
    ],
  },
]
