// Wiki articles — English. Section types: h2, p, list, steps, table, note.
export default [
  {
    slug: 'getting-started',
    icon: '🚀',
    title: 'Getting Started',
    summary: 'Install the plugin, set up Google Earth Engine, and authenticate.',
    sections: [
      { p: 'FARM tools is a QGIS plugin powered by Google Earth Engine (GEE). Before using any module you need QGIS 3.28 or newer, a free GEE account, and a Google Cloud project with the Earth Engine API enabled.' },
      { h2: 'Installation' },
      { steps: [
        'Open QGIS and go to Plugins → Manage and Install Plugins.',
        'Search for "FARM tools" and click Install.',
        'On first activation the plugin automatically downloads its dependency bundle (earthengine-api, agrigee-lite, and related packages). If the download fails it falls back to pip; just wait for the loading page to finish.',
      ] },
      { note: 'Dependencies are installed into the plugin\'s own extlibs folder and never shadow the packages shipped with QGIS (numpy, pandas, etc.). A QGIS/Python upgrade re-provisions them automatically.' },
      { h2: 'Google Earth Engine setup' },
      { steps: [
        'Create a free GEE account at earthengine.google.com/signup.',
        'Create a Google Cloud project at console.cloud.google.com and link it to your GEE account.',
        'In the Cloud Console, search for "Earth Engine API" and enable it.',
        'Open the Earth Engine Code Editor (code.earthengine.google.com) to find your project ID.',
        'In QGIS, open FARM tools, click Setup Authentication, enter the project ID, and authorize access in the browser window that opens.',
      ] },
      { h2: 'Authentication modes' },
      { p: 'FARM tools supports two ways of signing in to Earth Engine:' },
      { list: [
        'Personal OAuth — sign in with your Google account in the browser. Recommended for individual users.',
        'Service account — point the plugin to a service-account JSON key file. Recommended for shared machines, automation, or institutional accounts.',
      ] },
      { h2: 'Defining an area of interest (AOI)' },
      { p: 'Every module starts from an AOI. You can draw a polygon directly on the QGIS canvas with the built-in AOI tool, or select an existing vector layer. The AOI is converted to a WGS84 Earth Engine geometry internally, so any project CRS works.' },
      { note: 'If you previously used the RAVI plugin, your GEE project ID, auth mode, and download preferences carry over automatically — FARM tools shares those settings keys.' },
    ],
  },
  {
    slug: 'optical',
    icon: '🌿',
    title: 'Optical (Sentinel-2)',
    summary: 'Vegetation index time series, cloud filtering, composites, and multispectral download.',
    sections: [
      { p: 'The Optical module works with Sentinel-2 imagery: 10 m resolution, 5-day revisit, and 13 spectral bands. It is the workhorse for crop and vegetation monitoring.' },
      { h2: 'Vegetation index time series' },
      { p: 'Build a time series of a vegetation index over your AOI for any date range. Supported indices include:' },
      { list: [
        'NDVI — Normalized Difference Vegetation Index, the standard greenness measure.',
        'EVI — Enhanced Vegetation Index, less prone to saturation over dense canopies.',
        'SAVI — Soil-Adjusted Vegetation Index, corrects for soil brightness in sparse vegetation.',
        'GNDVI — Green NDVI, more sensitive to chlorophyll and nitrogen status.',
      ] },
      { p: 'The series can be computed per point or per feature (e.g. per field polygon), and results are shown as an interactive chart you can inspect date by date.' },
      { h2: 'Cloud filtering (SCL)' },
      { p: 'Cloudy observations distort time series. FARM tools uses the Sentinel-2 Scene Classification Layer (SCL) to mask clouds, shadows, and cirrus before computing indices, and lets you set a maximum cloud-cover threshold for the scenes included in the series.' },
      { h2: 'Image preview & composites' },
      { p: 'Preview any date as an RGB or index-colored image directly on the QGIS canvas before downloading. You can also build composites (e.g. median over a period) to obtain a cloud-free synthesis of your AOI.' },
      { h2: 'Multispectral download' },
      { p: 'Download the full multispectral stack (or selected bands) for your AOI as GeoTIFF, in batch, for one or many dates. Downloads run on a background thread, so QGIS stays responsive.' },
      { h2: 'Climate overlay' },
      { p: 'Optionally overlay NASA POWER climate series (precipitation, temperature) on the vegetation chart to interpret index dynamics against weather events — see the ClimaPlots article.' },
    ],
  },
  {
    slug: 'landsat',
    icon: '🛰️',
    title: 'Landsat',
    summary: 'Decades-long time series and imagery for historical monitoring.',
    sections: [
      { p: 'The Landsat module reaches back decades — Landsat 5, 7, 8, and 9 — making it the right choice for historical land-use analysis, long-term crop performance, and change detection beyond the Sentinel era (2015+).' },
      { h2: 'Long-term time series' },
      { p: 'Compute vegetation index time series across the full Landsat archive for your AOI. Use it to compare seasons across decades, detect degradation or recovery trends, and document land-use history for a parcel.' },
      { h2: 'Scene preview & download' },
      { p: 'Browse available scenes for your AOI and date range, preview them on the canvas, and download as GeoTIFF.' },
      { h2: 'Batch & super-resolution download' },
      { p: 'Powered by the agrigee-lite library, the module supports batch download of many scenes at once and super-resolution downloads that sharpen the native 30 m Landsat resolution for visual analysis.' },
      { note: 'Landsat revisit (16 days per satellite) and 30 m resolution make it coarser than Sentinel-2 — prefer the Optical module for current-season monitoring and Landsat for history.' },
    ],
  },
  {
    slug: 'sar',
    icon: '📡',
    title: 'SAR (Sentinel-1)',
    summary: 'Cloud-independent radar backscatter analysis for all-weather monitoring.',
    sections: [
      { p: 'Synthetic Aperture Radar (SAR) actively illuminates the ground with microwaves and measures the returned signal (backscatter). Unlike optical sensors, it works through clouds, smoke, and at night — essential during rainy seasons when optical series have gaps.' },
      { h2: 'What backscatter tells you' },
      { list: [
        'Surface roughness — tilled soil, growing canopy, and harvested fields return distinct signatures.',
        'Moisture — wet soil and vegetation reflect more strongly, useful for irrigation and flood monitoring.',
        'Structure — VV and VH polarizations respond differently to vertical stems versus leafy volume.',
      ] },
      { h2: 'Workflow' },
      { steps: [
        'Define your AOI and date range.',
        'Choose polarization (VV, VH) and orbit settings.',
        'Retrieve the backscatter series and inspect the interactive plot.',
        'Render any date as a styled layer on the canvas, or download the data.',
      ] },
      { h2: 'Date filtering & plotting' },
      { p: 'The module lists available Sentinel-1 acquisitions for your AOI, lets you filter by date, and plots backscatter evolution per polarization. Styled rendering applies a ready-made symbology so radar images are interpretable at first glance.' },
      { note: 'SAR values are in decibels (dB) and typically negative — e.g. −18 dB for bare soil, −10 dB for dense canopy. Relative change over time matters more than absolute values.' },
    ],
  },
  {
    slug: 'dem',
    icon: '⛰️',
    title: 'DEM & Terrain',
    summary: 'Elevation catalog browsing, downloads, and terrain rendering.',
    sections: [
      { p: 'The DEM module downloads Digital Elevation Models for any AOI and derives terrain visualizations — the base layer for drainage planning, terracing, machine guidance, and erosion analysis.' },
      { h2: 'Elevation catalog' },
      { p: 'Browse a catalog of global and regional elevation datasets (e.g. SRTM, Copernicus DEM and other GEE-hosted sources), check availability for your AOI, and pick the resolution that fits your purpose.' },
      { h2: 'Download' },
      { p: 'Select the dataset and AOI, and the module downloads a clipped GeoTIFF on a background thread. Availability is verified up front so you do not wait on an empty request.' },
      { h2: 'Terrain products' },
      { p: 'After download, FARM tools can render the DEM as hillshade and styled terrain layers directly in QGIS, providing immediate visual relief without manual symbology work.' },
      { note: 'For agricultural micro-topography (e.g. 1 m precision leveling) survey-grade data is still required — public DEMs resolve macro relief (10–30 m grids).' },
    ],
  },
  {
    slug: 'sysi',
    icon: '🟤',
    title: 'SYSI Bare Soil',
    summary: 'Synthetic bare-soil image composites for soil mapping.',
    sections: [
      { p: 'SYSI (Synthetic Soil Image) builds a composite where every pixel shows the soil surface free of vegetation — even though no single date shows the whole area bare. It is a key input for digital soil mapping, soil-class delineation, and management zones.' },
      { h2: 'How it works' },
      { steps: [
        'The module scans a multi-year stack of satellite images over your AOI.',
        'For each pixel, the GEOS3 method (Geospatial Soil Sensing System) detects the dates when that pixel was bare soil, using spectral rules that separate bare soil from vegetation, straw, and clouds.',
        'The bare observations are combined per pixel into a single synthetic composite.',
        'The result is rendered in QGIS and can be exported as GeoTIFF.',
      ] },
      { h2: 'What you can do with a SYSI' },
      { list: [
        'Delineate soil classes and transitions visually — color differences track texture and organic matter.',
        'Support sampling design: place soil samples where the composite shows distinct zones.',
        'Feed digital soil mapping models with a stable spectral predictor.',
      ] },
      { note: 'Areas that were never bare during the analyzed period (permanent pasture, forest) stay empty in the composite — extend the date range to improve coverage.' },
    ],
  },
  {
    slug: 'climaplots',
    icon: '🌦️',
    title: 'ClimaPlots',
    summary: 'NASA POWER climate series and charts.',
    sections: [
      { p: 'ClimaPlots fetches climate series from NASA POWER — a global, free reanalysis dataset — for your AOI and plots them as interactive charts inside QGIS. No weather station required.' },
      { h2: 'Available variables' },
      { list: [
        'Precipitation',
        'Air temperature (min / max / mean)',
        'Solar radiation',
        'Relative humidity and wind speed',
      ] },
      { h2: 'Typical uses' },
      { list: [
        'Explain anomalies in NDVI series — drops after frost, plateaus during drought.',
        'Compare season rainfall against historical averages before planning.',
        'Document weather context in field reports.',
      ] },
      { p: 'In the Optical module the climate series can be overlaid directly on the vegetation index chart, aligning crop response with rainfall and temperature on the same time axis.' },
      { note: 'NASA POWER cells are ~0.5° (≈50 km), representing regional climate rather than farm-scale microclimate. For within-farm variability use local sensors.' },
    ],
  },
  {
    slug: 'fieldguide',
    icon: '📍',
    title: 'Field Guide',
    summary: 'Field point capture, polygon sampling, raster-optimal points, routes, and exports.',
    sections: [
      { p: 'Field Guide turns the QGIS canvas into a field-campaign planner: capture sampling points, generate them automatically from polygon parcels (geometric or raster-optimized), open driving routes, and export the session as CSV, GPX, a QGIS layer, or a phone-friendly PDF report.' },
      { p: 'All points are stored internally in WGS84 (EPSG:4326) regardless of the project CRS, with 8-decimal precision (~1 mm) — coordinates round-trip losslessly through every export.' },
      { h2: 'Manual capture & coordinate entry' },
      { list: [
        'Capture points on map: each canvas click adds a numbered marker. The tool restores the previous map tool when toggled off and never permanently hijacks the canvas.',
        'Manual entry: type latitude/longitude directly. Both dot and comma decimals are accepted (-23,5505 ≡ -23.5505), with range validation.',
      ] },
      { h2: 'Polygon sampling (geometric)' },
      { p: 'Generate sample points for every feature of a polygon layer. Quantity is either a fixed count per feature (1–50) or a density (one mark per N hectares, measured ellipsoidally). Distribution methods:' },
      { list: [
        'Centroid — one point at the polygon centroid; fast for compact parcels.',
        'Spread optimized (default) — greedy maximin selection approximating a space-filling design, robust on irregular shapes; output sorted for a stable walking order.',
        'Systematic grid — a grid aligned with the parcel\'s long axis (via PCA of the candidate cloud), not with map north.',
        'Zigzag transect — the classic serpentine soil-sampling walk along the parcel\'s major axis.',
      ] },
      { p: 'Points are kept away from parcel borders by an automatic inward buffer (3–12% of the parcel size), avoiding edge effects like mixed pixels and machinery turn rows. Sampling is deterministic: the same layer, method, and count always produce the same points, so plans are reproducible and auditable.' },
      { h2: 'Raster-based optimal points' },
      { p: 'Instead of geometric placement, let the data decide: one point per polygon at the location of the maximum raster value (e.g. an NDVI composite peak), so field workers visit the most physiologically representative spot of each parcel.' },
      { steps: [
        'Enable "Use raster-based optimal point selection".',
        'Pick the raster layer and band.',
        'Points are computed immediately — the polygon is reprojected to the raster CRS (the raster is never resampled), masked to the exact geometry, cleaned of no-data and edge noise, and the smoothed maximum is selected.',
      ] },
      { p: 'Edge cases are handled explicitly: fully clouded polygons are skipped and counted, sub-pixel polygons are flagged, and web/tile basemaps (XYZ, WMS) are rejected up front since they have no readable pixel grid. Raster name, band, CRS, and the value at each point flow into every export for full traceability.' },
      { h2: 'Routes (Google Maps)' },
      { p: 'Open the session points as an ordered driving route in Google Maps. Long sessions are split into 10-point segments with a 1-point overlap, so multi-segment routes stay continuous.' },
      { h2: 'Exports' },
      { table: {
        headers: ['Format', 'Contents'],
        rows: [
          ['CSV', 'order, longitude, latitude (8 decimals); raster source, method, and value columns when raster selection was used'],
          ['GPX', 'Waypoints FG001…FGnnn (GPS-handheld friendly) plus an ordered route; raster metadata in waypoint descriptions'],
          ['Temporary layer', 'In-memory point layer in the project CRS with order/name/lon/lat attributes'],
          ['PDF report', 'Canvas snapshot plus one tap-target card per point linking to Google Maps; raster methodology footer when applicable'],
        ],
      } },
      { h2: 'Session management' },
      { list: [
        'Live point list with count and route readiness.',
        'Remove last, delete selected (numbering stays contiguous), and clear with confirmation.',
        'Append / Replace prompt protects existing work when generating or importing into a non-empty session.',
        'CSV import: requires longitude/latitude headers (any order, case-insensitive), accepts comma decimals, reports skipped rows.',
      ] },
    ],
  },
  {
    slug: 'mapbiomas',
    icon: '🗺️',
    title: 'MapBiomas',
    summary: 'Brazilian land-use/land-cover by year and configurable transition analysis.',
    sections: [
      { p: 'MapBiomas brings the MapBiomas Brasil Collection 9 annual land-use / land-cover archive into QGIS. Browse any year inside the module, download a year to QGIS as a styled classification raster, or analyze how the land changed over time. Coverage is Brazil-only and runs through Google Earth Engine.' },
      { h2: 'Coverage' },
      { list: [
        'Browse every year (1985–2023) in-module with a year slider, beside the official 63-class legend.',
        'Download any single year to QGIS as a single-band classification raster styled with the official MapBiomas palette — real class IDs, so pixels stay queryable and analyzable.',
      ] },
      { h2: 'Transition analysis' },
      { p: 'Map the first year each pixel changed from a source land-use to a target land-use, and chart the converted area per year.' },
      { list: [
        'Presets: Pasture → Crop, Deforestation (forest → anthropic), Forest regrowth, Agricultural expansion, and Urban expansion.',
        'Custom: pick any combination of source and target classes.',
        'A year-range slider filters the chart live and limits the exported transition layer, which loads into QGIS classed by transition year.',
      ] },
      { note: 'MapBiomas Collection 9 covers Brazil only — areas outside Brazil return empty results. Requires Google Earth Engine authentication, like the other GEE modules.' },
    ],
  },
  {
    slug: 'exports-downloads',
    icon: '💾',
    title: 'Exports & Downloads',
    summary: 'Output formats across all modules and where files are saved.',
    sections: [
      { p: 'Every FARM tools module produces standard, portable formats that open in QGIS and beyond.' },
      { table: {
        headers: ['Module', 'Outputs'],
        rows: [
          ['Optical', 'Index time series (chart + CSV), GeoTIFF imagery and composites, multispectral batch download'],
          ['Landsat', 'Time series, GeoTIFF scenes, batch and super-resolution downloads'],
          ['SAR', 'Backscatter series and plots, styled raster layers, GeoTIFF download'],
          ['DEM', 'Clipped GeoTIFF elevation, hillshade/terrain rendering'],
          ['SYSI', 'Synthetic bare-soil composite as a rendered layer / GeoTIFF'],
          ['ClimaPlots', 'Climate series charts and data'],
          ['Field Guide', 'CSV, GPX, temporary QGIS layer, PDF report, Google Maps routes'],
          ['MapBiomas', 'Classification GeoTIFF per year and transition GeoTIFF (classed by transition year), styled paletted layers'],
        ],
      } },
      { h2: 'Download folder & proxy' },
      { p: 'The default download folder and an optional HTTP(S) proxy are configured in the plugin settings and persist across sessions. All heavy downloads run on background threads — you can keep working in QGIS while they complete.' },
    ],
  },
  {
    slug: 'faq',
    icon: '❓',
    title: 'FAQ & Troubleshooting',
    summary: 'Common problems: authentication, dependencies, proxies, and coexistence with RAVI.',
    sections: [
      { h2: 'Authentication fails or asks again every session' },
      { list: [
        'Confirm the Earth Engine API is enabled for your Cloud project (Cloud Console → APIs).',
        'Confirm the project ID is the Cloud project ID, not the project name.',
        'Personal OAuth opens a browser window — if it never appears, check your default browser and any popup blockers.',
        'For service accounts: the JSON key path must be readable and the service account must be registered for Earth Engine use.',
      ] },
      { h2: 'Dependency installation problems' },
      { list: [
        'First launch downloads a prebuilt dependency bundle matched to your QGIS Python version; on failure it falls back to pip. Both need internet access.',
        'Behind a corporate firewall, set the proxy URL in the plugin settings and restart QGIS.',
        'After a QGIS upgrade (new Python version) dependencies are re-provisioned automatically on next launch.',
      ] },
      { h2: 'Charts or downloads stay empty' },
      { list: [
        'Check the AOI actually intersects available imagery for the selected date range.',
        'For Sentinel-2, a strict cloud threshold can filter out every scene — relax it and retry.',
        'GEE has usage quotas; very large AOIs or long ranges may need to be split.',
      ] },
      { h2: 'Can I run FARM tools next to RAVI?' },
      { p: 'Yes. FARM tools is a fork of the RAVI plugin with its own identity (folder, menu, toolbar) and is designed to run side-by-side with RAVI in the same QGIS profile. GEE sign-in and download preferences are intentionally shared, so an existing RAVI setup carries over.' },
      { h2: 'Which QGIS versions are supported?' },
      { p: 'QGIS 3.28 or newer (Python 3.11–3.13). The QGIS 3.44 LTR with Python 3.12 is the reference platform.' },
      { h2: 'Where do I report bugs or ask for features?' },
      { p: 'Open an issue at github.com/farmanalytica/farm_tools/issues. For commercial support and custom solutions, contact FARM Analytica via WhatsApp or adm@farmanalytica.com.br.' },
    ],
  },
]
